// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CustomField custom field
//
// swagger:model CustomField
type CustomField struct {

	// choice set
	ChoiceSet *CustomFieldChoiceSet `json:"choice_set,omitempty"`

	// content types
	// Unique: true
	ContentTypes []string `json:"content_types,omitempty"`

	// Created
	// Read Only: true
	// Format: date-time
	Created *strfmt.DateTime `json:"created,omitempty"`

	// Data type
	// Read Only: true
	DataType string `json:"data_type,omitempty"`

	// Default
	//
	// Default value for the field (must be a JSON value). Encapsulate strings with double quotes (e.g. "Foo").
	Default interface{} `json:"default,omitempty"`

	// Description
	// Max Length: 200
	Description string `json:"description,omitempty"`

	// Display
	// Read Only: true
	Display string `json:"display,omitempty"`

	// filter logic
	FilterLogic *CustomFieldFilterLogic `json:"filter_logic,omitempty"`

	// Group name
	//
	// Custom fields within the same group will be displayed together
	// Max Length: 50
	GroupName string `json:"group_name,omitempty"`

	// ID
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Label
	//
	// Name of the field as displayed to users (if not provided, the field's name will be used)
	// Max Length: 50
	Label string `json:"label,omitempty"`

	// Last updated
	// Read Only: true
	// Format: date-time
	LastUpdated *strfmt.DateTime `json:"last_updated,omitempty"`

	// Name
	//
	// Internal field name
	// Required: true
	// Max Length: 50
	// Min Length: 1
	// Pattern: ^[a-z0-9_]+$
	Name *string `json:"name"`

	// Object type
	ObjectType string `json:"object_type,omitempty"`

	// object types
	// Unique: true
	ObjectTypes []string `json:"object_types,omitempty"`

	// Related object type
	// Enum: ["circuits.circuit","circuits.circuittermination","circuits.virtualcircuit","circuits.virtualcircuittermination","core.datasource","core.job","core.objectchange","dcim.cable","dcim.cablepath","dcim.cabletermination","dcim.consoleport","dcim.consoleporttemplate","dcim.consoleserverport","dcim.consoleserverporttemplate","dcim.device","dcim.devicebay","dcim.devicebaytemplate","dcim.devicerole","dcim.devicetype","dcim.frontport","dcim.frontporttemplate","dcim.interface","dcim.interfacetemplate","dcim.inventoryitem","dcim.inventoryitemrole","dcim.inventoryitemtemplate","dcim.location","dcim.manufacturer","dcim.module","dcim.modulebay","dcim.modulebaytemplate","dcim.moduletype","dcim.platform","dcim.powerfeed","dcim.poweroutlet","dcim.poweroutlettemplate","dcim.powerpanel","dcim.powerport","dcim.powerporttemplate","dcim.rack","dcim.rackreservation","dcim.rackrole","dcim.rearport","dcim.rearporttemplate","dcim.region","dcim.site","dcim.sitegroup","dcim.virtualchassis","extras.configcontext","extras.configrevision","extras.customfield","extras.customlink","extras.exporttemplate","extras.imageattachment","extras.jobresult","extras.journalentry","extras.report","extras.script","extras.tag","extras.taggeditem","extras.webhook","ipam.aggregate","ipam.ASN","ipam.FHRPgroup","ipam.FHRPgroupassignment","ipam.IPaddress","ipam.IPrange","ipam.L2VPN","ipam.L2VPNtermination","ipam.prefix","ipam.RIR","ipam.role","ipam.routetarget","ipam.service","ipam.servicetemplate","ipam.VLAN","ipam.VLANgroup","ipam.VRF","tenancy.contact","tenancy.contactassignment","tenancy.contactgroup","tenancy.contactrole","tenancy.tenant","tenancy.tenantgroup","virtualization.cluster","virtualization.clustergroup","virtualization.clustertype","virtualization.interface","virtualization.virtualmachine","wireless.WirelessLAN","wireless.WirelessLANGroup","wireless.wirelesslink"]
	RelatedObjectType string `json:"related_object_type,omitempty"`

	// Required
	//
	// If true, this field is required when creating new objects or editing an existing object.
	Required bool `json:"required,omitempty"`

	// Search weight
	//
	// Weighting for search. Lower values are considered more important. Fields with a search weight of zero will be ignored.
	// Maximum: 32767
	// Minimum: 0
	SearchWeight *int64 `json:"search_weight,omitempty"`

	// type
	// Required: true
	Type *CustomFieldType `json:"type"`

	// ui visibility
	UIVisibility *CustomFieldUIVisibility `json:"ui_visibility,omitempty"`

	// Url
	// Read Only: true
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// Maximum value
	//
	// Maximum allowed value (for numeric fields)
	// Maximum: 2.147483647e+09
	// Minimum: -2.147483648e+09
	ValidationMaximum *float64 `json:"validation_maximum,omitempty"`

	// Minimum value
	//
	// Minimum allowed value (for numeric fields)
	// Maximum: 2.147483647e+09
	// Minimum: -2.147483648e+09
	ValidationMinimum *float64 `json:"validation_minimum,omitempty"`

	// Validation regex
	//
	// Regular expression to enforce on text field values. Use ^ and $ to force matching of entire string. For example, <code>^[A-Z]{3}$</code> will limit values to exactly three uppercase letters.
	// Max Length: 500
	ValidationRegex string `json:"validation_regex,omitempty"`

	// Display weight
	//
	// Fields with higher weights appear lower in a form.
	// Maximum: 32767
	// Minimum: 0
	Weight *int64 `json:"weight,omitempty"`
}

// Validate validates this custom field
func (m *CustomField) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChoiceSet(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateContentTypes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilterLogic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObjectTypes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelatedObjectType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSearchWeight(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUIVisibility(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationMaximum(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationMinimum(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationRegex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWeight(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustomField) validateChoiceSet(formats strfmt.Registry) error {
	if swag.IsZero(m.ChoiceSet) { // not required
		return nil
	}

	if m.ChoiceSet != nil {
		if err := m.ChoiceSet.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("choice_set")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("choice_set")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) validateContentTypes(formats strfmt.Registry) error {
	if swag.IsZero(m.ContentTypes) { // not required
		return nil
	}

	if err := validate.UniqueItems("content_types", "body", m.ContentTypes); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description, 200); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateFilterLogic(formats strfmt.Registry) error {
	if swag.IsZero(m.FilterLogic) { // not required
		return nil
	}

	if m.FilterLogic != nil {
		if err := m.FilterLogic.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filter_logic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filter_logic")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) validateGroupName(formats strfmt.Registry) error {
	if swag.IsZero(m.GroupName) { // not required
		return nil
	}

	if err := validate.MaxLength("group_name", "body", m.GroupName, 50); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateLabel(formats strfmt.Registry) error {
	if swag.IsZero(m.Label) { // not required
		return nil
	}

	if err := validate.MaxLength("label", "body", m.Label, 50); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateLastUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.LastUpdated) { // not required
		return nil
	}

	if err := validate.FormatOf("last_updated", "body", "date-time", m.LastUpdated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 50); err != nil {
		return err
	}

	if err := validate.Pattern("name", "body", *m.Name, `^[a-z0-9_]+$`); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateObjectTypes(formats strfmt.Registry) error {
	if swag.IsZero(m.ObjectTypes) { // not required
		return nil
	}

	if err := validate.UniqueItems("object_types", "body", m.ObjectTypes); err != nil {
		return err
	}

	return nil
}

var customFieldTypeRelatedObjectTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["circuits.circuit","circuits.circuittermination","circuits.virtualcircuit","circuits.virtualcircuittermination","core.datasource","core.job","core.objectchange","dcim.cable","dcim.cablepath","dcim.cabletermination","dcim.consoleport","dcim.consoleporttemplate","dcim.consoleserverport","dcim.consoleserverporttemplate","dcim.device","dcim.devicebay","dcim.devicebaytemplate","dcim.devicerole","dcim.devicetype","dcim.frontport","dcim.frontporttemplate","dcim.interface","dcim.interfacetemplate","dcim.inventoryitem","dcim.inventoryitemrole","dcim.inventoryitemtemplate","dcim.location","dcim.manufacturer","dcim.module","dcim.modulebay","dcim.modulebaytemplate","dcim.moduletype","dcim.platform","dcim.powerfeed","dcim.poweroutlet","dcim.poweroutlettemplate","dcim.powerpanel","dcim.powerport","dcim.powerporttemplate","dcim.rack","dcim.rackreservation","dcim.rackrole","dcim.rearport","dcim.rearporttemplate","dcim.region","dcim.site","dcim.sitegroup","dcim.virtualchassis","extras.configcontext","extras.configrevision","extras.customfield","extras.customlink","extras.exporttemplate","extras.imageattachment","extras.jobresult","extras.journalentry","extras.report","extras.script","extras.tag","extras.taggeditem","extras.webhook","ipam.aggregate","ipam.ASN","ipam.FHRPgroup","ipam.FHRPgroupassignment","ipam.IPaddress","ipam.IPrange","ipam.L2VPN","ipam.L2VPNtermination","ipam.prefix","ipam.RIR","ipam.role","ipam.routetarget","ipam.service","ipam.servicetemplate","ipam.VLAN","ipam.VLANgroup","ipam.VRF","tenancy.contact","tenancy.contactassignment","tenancy.contactgroup","tenancy.contactrole","tenancy.tenant","tenancy.tenantgroup","virtualization.cluster","virtualization.clustergroup","virtualization.clustertype","virtualization.interface","virtualization.virtualmachine","wireless.WirelessLAN","wireless.WirelessLANGroup","wireless.wirelesslink"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customFieldTypeRelatedObjectTypePropEnum = append(customFieldTypeRelatedObjectTypePropEnum, v)
	}
}

const (

	// CustomFieldRelatedObjectTypeCircuitsDotCircuit captures enum value "circuits.circuit"
	CustomFieldRelatedObjectTypeCircuitsDotCircuit string = "circuits.circuit"

	// CustomFieldRelatedObjectTypeCircuitsDotCircuittermination captures enum value "circuits.circuittermination"
	CustomFieldRelatedObjectTypeCircuitsDotCircuittermination string = "circuits.circuittermination"

	// CustomFieldRelatedObjectTypeCircuitsDotVirtualcircuit captures enum value "circuits.virtualcircuit"
	CustomFieldRelatedObjectTypeCircuitsDotVirtualcircuit string = "circuits.virtualcircuit"

	// CustomFieldRelatedObjectTypeCircuitsDotVirtualcircuittermination captures enum value "circuits.virtualcircuittermination"
	CustomFieldRelatedObjectTypeCircuitsDotVirtualcircuittermination string = "circuits.virtualcircuittermination"

	// CustomFieldRelatedObjectTypeCoreDotDatasource captures enum value "core.datasource"
	CustomFieldRelatedObjectTypeCoreDotDatasource string = "core.datasource"

	// CustomFieldRelatedObjectTypeCoreDotJob captures enum value "core.job"
	CustomFieldRelatedObjectTypeCoreDotJob string = "core.job"

	// CustomFieldRelatedObjectTypeCoreDotObjectchange captures enum value "core.objectchange"
	CustomFieldRelatedObjectTypeCoreDotObjectchange string = "core.objectchange"

	// CustomFieldRelatedObjectTypeDcimDotCable captures enum value "dcim.cable"
	CustomFieldRelatedObjectTypeDcimDotCable string = "dcim.cable"

	// CustomFieldRelatedObjectTypeDcimDotCablepath captures enum value "dcim.cablepath"
	CustomFieldRelatedObjectTypeDcimDotCablepath string = "dcim.cablepath"

	// CustomFieldRelatedObjectTypeDcimDotCabletermination captures enum value "dcim.cabletermination"
	CustomFieldRelatedObjectTypeDcimDotCabletermination string = "dcim.cabletermination"

	// CustomFieldRelatedObjectTypeDcimDotConsoleport captures enum value "dcim.consoleport"
	CustomFieldRelatedObjectTypeDcimDotConsoleport string = "dcim.consoleport"

	// CustomFieldRelatedObjectTypeDcimDotConsoleporttemplate captures enum value "dcim.consoleporttemplate"
	CustomFieldRelatedObjectTypeDcimDotConsoleporttemplate string = "dcim.consoleporttemplate"

	// CustomFieldRelatedObjectTypeDcimDotConsoleserverport captures enum value "dcim.consoleserverport"
	CustomFieldRelatedObjectTypeDcimDotConsoleserverport string = "dcim.consoleserverport"

	// CustomFieldRelatedObjectTypeDcimDotConsoleserverporttemplate captures enum value "dcim.consoleserverporttemplate"
	CustomFieldRelatedObjectTypeDcimDotConsoleserverporttemplate string = "dcim.consoleserverporttemplate"

	// CustomFieldRelatedObjectTypeDcimDotDevice captures enum value "dcim.device"
	CustomFieldRelatedObjectTypeDcimDotDevice string = "dcim.device"

	// CustomFieldRelatedObjectTypeDcimDotDevicebay captures enum value "dcim.devicebay"
	CustomFieldRelatedObjectTypeDcimDotDevicebay string = "dcim.devicebay"

	// CustomFieldRelatedObjectTypeDcimDotDevicebaytemplate captures enum value "dcim.devicebaytemplate"
	CustomFieldRelatedObjectTypeDcimDotDevicebaytemplate string = "dcim.devicebaytemplate"

	// CustomFieldRelatedObjectTypeDcimDotDevicerole captures enum value "dcim.devicerole"
	CustomFieldRelatedObjectTypeDcimDotDevicerole string = "dcim.devicerole"

	// CustomFieldRelatedObjectTypeDcimDotDevicetype captures enum value "dcim.devicetype"
	CustomFieldRelatedObjectTypeDcimDotDevicetype string = "dcim.devicetype"

	// CustomFieldRelatedObjectTypeDcimDotFrontport captures enum value "dcim.frontport"
	CustomFieldRelatedObjectTypeDcimDotFrontport string = "dcim.frontport"

	// CustomFieldRelatedObjectTypeDcimDotFrontporttemplate captures enum value "dcim.frontporttemplate"
	CustomFieldRelatedObjectTypeDcimDotFrontporttemplate string = "dcim.frontporttemplate"

	// CustomFieldRelatedObjectTypeDcimDotInterface captures enum value "dcim.interface"
	CustomFieldRelatedObjectTypeDcimDotInterface string = "dcim.interface"

	// CustomFieldRelatedObjectTypeDcimDotInterfacetemplate captures enum value "dcim.interfacetemplate"
	CustomFieldRelatedObjectTypeDcimDotInterfacetemplate string = "dcim.interfacetemplate"

	// CustomFieldRelatedObjectTypeDcimDotInventoryitem captures enum value "dcim.inventoryitem"
	CustomFieldRelatedObjectTypeDcimDotInventoryitem string = "dcim.inventoryitem"

	// CustomFieldRelatedObjectTypeDcimDotInventoryitemrole captures enum value "dcim.inventoryitemrole"
	CustomFieldRelatedObjectTypeDcimDotInventoryitemrole string = "dcim.inventoryitemrole"

	// CustomFieldRelatedObjectTypeDcimDotInventoryitemtemplate captures enum value "dcim.inventoryitemtemplate"
	CustomFieldRelatedObjectTypeDcimDotInventoryitemtemplate string = "dcim.inventoryitemtemplate"

	// CustomFieldRelatedObjectTypeDcimDotLocation captures enum value "dcim.location"
	CustomFieldRelatedObjectTypeDcimDotLocation string = "dcim.location"

	// CustomFieldRelatedObjectTypeDcimDotManufacturer captures enum value "dcim.manufacturer"
	CustomFieldRelatedObjectTypeDcimDotManufacturer string = "dcim.manufacturer"

	// CustomFieldRelatedObjectTypeDcimDotModule captures enum value "dcim.module"
	CustomFieldRelatedObjectTypeDcimDotModule string = "dcim.module"

	// CustomFieldRelatedObjectTypeDcimDotModulebay captures enum value "dcim.modulebay"
	CustomFieldRelatedObjectTypeDcimDotModulebay string = "dcim.modulebay"

	// CustomFieldRelatedObjectTypeDcimDotModulebaytemplate captures enum value "dcim.modulebaytemplate"
	CustomFieldRelatedObjectTypeDcimDotModulebaytemplate string = "dcim.modulebaytemplate"

	// CustomFieldRelatedObjectTypeDcimDotModuletype captures enum value "dcim.moduletype"
	CustomFieldRelatedObjectTypeDcimDotModuletype string = "dcim.moduletype"

	// CustomFieldRelatedObjectTypeDcimDotPlatform captures enum value "dcim.platform"
	CustomFieldRelatedObjectTypeDcimDotPlatform string = "dcim.platform"

	// CustomFieldRelatedObjectTypeDcimDotPowerfeed captures enum value "dcim.powerfeed"
	CustomFieldRelatedObjectTypeDcimDotPowerfeed string = "dcim.powerfeed"

	// CustomFieldRelatedObjectTypeDcimDotPoweroutlet captures enum value "dcim.poweroutlet"
	CustomFieldRelatedObjectTypeDcimDotPoweroutlet string = "dcim.poweroutlet"

	// CustomFieldRelatedObjectTypeDcimDotPoweroutlettemplate captures enum value "dcim.poweroutlettemplate"
	CustomFieldRelatedObjectTypeDcimDotPoweroutlettemplate string = "dcim.poweroutlettemplate"

	// CustomFieldRelatedObjectTypeDcimDotPowerpanel captures enum value "dcim.powerpanel"
	CustomFieldRelatedObjectTypeDcimDotPowerpanel string = "dcim.powerpanel"

	// CustomFieldRelatedObjectTypeDcimDotPowerport captures enum value "dcim.powerport"
	CustomFieldRelatedObjectTypeDcimDotPowerport string = "dcim.powerport"

	// CustomFieldRelatedObjectTypeDcimDotPowerporttemplate captures enum value "dcim.powerporttemplate"
	CustomFieldRelatedObjectTypeDcimDotPowerporttemplate string = "dcim.powerporttemplate"

	// CustomFieldRelatedObjectTypeDcimDotRack captures enum value "dcim.rack"
	CustomFieldRelatedObjectTypeDcimDotRack string = "dcim.rack"

	// CustomFieldRelatedObjectTypeDcimDotRackreservation captures enum value "dcim.rackreservation"
	CustomFieldRelatedObjectTypeDcimDotRackreservation string = "dcim.rackreservation"

	// CustomFieldRelatedObjectTypeDcimDotRackrole captures enum value "dcim.rackrole"
	CustomFieldRelatedObjectTypeDcimDotRackrole string = "dcim.rackrole"

	// CustomFieldRelatedObjectTypeDcimDotRearport captures enum value "dcim.rearport"
	CustomFieldRelatedObjectTypeDcimDotRearport string = "dcim.rearport"

	// CustomFieldRelatedObjectTypeDcimDotRearporttemplate captures enum value "dcim.rearporttemplate"
	CustomFieldRelatedObjectTypeDcimDotRearporttemplate string = "dcim.rearporttemplate"

	// CustomFieldRelatedObjectTypeDcimDotRegion captures enum value "dcim.region"
	CustomFieldRelatedObjectTypeDcimDotRegion string = "dcim.region"

	// CustomFieldRelatedObjectTypeDcimDotSite captures enum value "dcim.site"
	CustomFieldRelatedObjectTypeDcimDotSite string = "dcim.site"

	// CustomFieldRelatedObjectTypeDcimDotSitegroup captures enum value "dcim.sitegroup"
	CustomFieldRelatedObjectTypeDcimDotSitegroup string = "dcim.sitegroup"

	// CustomFieldRelatedObjectTypeDcimDotVirtualchassis captures enum value "dcim.virtualchassis"
	CustomFieldRelatedObjectTypeDcimDotVirtualchassis string = "dcim.virtualchassis"

	// CustomFieldRelatedObjectTypeExtrasDotConfigcontext captures enum value "extras.configcontext"
	CustomFieldRelatedObjectTypeExtrasDotConfigcontext string = "extras.configcontext"

	// CustomFieldRelatedObjectTypeExtrasDotConfigrevision captures enum value "extras.configrevision"
	CustomFieldRelatedObjectTypeExtrasDotConfigrevision string = "extras.configrevision"

	// CustomFieldRelatedObjectTypeExtrasDotCustomfield captures enum value "extras.customfield"
	CustomFieldRelatedObjectTypeExtrasDotCustomfield string = "extras.customfield"

	// CustomFieldRelatedObjectTypeExtrasDotCustomlink captures enum value "extras.customlink"
	CustomFieldRelatedObjectTypeExtrasDotCustomlink string = "extras.customlink"

	// CustomFieldRelatedObjectTypeExtrasDotExporttemplate captures enum value "extras.exporttemplate"
	CustomFieldRelatedObjectTypeExtrasDotExporttemplate string = "extras.exporttemplate"

	// CustomFieldRelatedObjectTypeExtrasDotImageattachment captures enum value "extras.imageattachment"
	CustomFieldRelatedObjectTypeExtrasDotImageattachment string = "extras.imageattachment"

	// CustomFieldRelatedObjectTypeExtrasDotJobresult captures enum value "extras.jobresult"
	CustomFieldRelatedObjectTypeExtrasDotJobresult string = "extras.jobresult"

	// CustomFieldRelatedObjectTypeExtrasDotJournalentry captures enum value "extras.journalentry"
	CustomFieldRelatedObjectTypeExtrasDotJournalentry string = "extras.journalentry"

	// CustomFieldRelatedObjectTypeExtrasDotReport captures enum value "extras.report"
	CustomFieldRelatedObjectTypeExtrasDotReport string = "extras.report"

	// CustomFieldRelatedObjectTypeExtrasDotScript captures enum value "extras.script"
	CustomFieldRelatedObjectTypeExtrasDotScript string = "extras.script"

	// CustomFieldRelatedObjectTypeExtrasDotTag captures enum value "extras.tag"
	CustomFieldRelatedObjectTypeExtrasDotTag string = "extras.tag"

	// CustomFieldRelatedObjectTypeExtrasDotTaggeditem captures enum value "extras.taggeditem"
	CustomFieldRelatedObjectTypeExtrasDotTaggeditem string = "extras.taggeditem"

	// CustomFieldRelatedObjectTypeExtrasDotWebhook captures enum value "extras.webhook"
	CustomFieldRelatedObjectTypeExtrasDotWebhook string = "extras.webhook"

	// CustomFieldRelatedObjectTypeIpamDotAggregate captures enum value "ipam.aggregate"
	CustomFieldRelatedObjectTypeIpamDotAggregate string = "ipam.aggregate"

	// CustomFieldRelatedObjectTypeIpamDotASN captures enum value "ipam.ASN"
	CustomFieldRelatedObjectTypeIpamDotASN string = "ipam.ASN"

	// CustomFieldRelatedObjectTypeIpamDotFHRPgroup captures enum value "ipam.FHRPgroup"
	CustomFieldRelatedObjectTypeIpamDotFHRPgroup string = "ipam.FHRPgroup"

	// CustomFieldRelatedObjectTypeIpamDotFHRPgroupassignment captures enum value "ipam.FHRPgroupassignment"
	CustomFieldRelatedObjectTypeIpamDotFHRPgroupassignment string = "ipam.FHRPgroupassignment"

	// CustomFieldRelatedObjectTypeIpamDotIPaddress captures enum value "ipam.IPaddress"
	CustomFieldRelatedObjectTypeIpamDotIPaddress string = "ipam.IPaddress"

	// CustomFieldRelatedObjectTypeIpamDotIPrange captures enum value "ipam.IPrange"
	CustomFieldRelatedObjectTypeIpamDotIPrange string = "ipam.IPrange"

	// CustomFieldRelatedObjectTypeIpamDotL2VPN captures enum value "ipam.L2VPN"
	CustomFieldRelatedObjectTypeIpamDotL2VPN string = "ipam.L2VPN"

	// CustomFieldRelatedObjectTypeIpamDotL2VPNtermination captures enum value "ipam.L2VPNtermination"
	CustomFieldRelatedObjectTypeIpamDotL2VPNtermination string = "ipam.L2VPNtermination"

	// CustomFieldRelatedObjectTypeIpamDotPrefix captures enum value "ipam.prefix"
	CustomFieldRelatedObjectTypeIpamDotPrefix string = "ipam.prefix"

	// CustomFieldRelatedObjectTypeIpamDotRIR captures enum value "ipam.RIR"
	CustomFieldRelatedObjectTypeIpamDotRIR string = "ipam.RIR"

	// CustomFieldRelatedObjectTypeIpamDotRole captures enum value "ipam.role"
	CustomFieldRelatedObjectTypeIpamDotRole string = "ipam.role"

	// CustomFieldRelatedObjectTypeIpamDotRoutetarget captures enum value "ipam.routetarget"
	CustomFieldRelatedObjectTypeIpamDotRoutetarget string = "ipam.routetarget"

	// CustomFieldRelatedObjectTypeIpamDotService captures enum value "ipam.service"
	CustomFieldRelatedObjectTypeIpamDotService string = "ipam.service"

	// CustomFieldRelatedObjectTypeIpamDotServicetemplate captures enum value "ipam.servicetemplate"
	CustomFieldRelatedObjectTypeIpamDotServicetemplate string = "ipam.servicetemplate"

	// CustomFieldRelatedObjectTypeIpamDotVLAN captures enum value "ipam.VLAN"
	CustomFieldRelatedObjectTypeIpamDotVLAN string = "ipam.VLAN"

	// CustomFieldRelatedObjectTypeIpamDotVLANgroup captures enum value "ipam.VLANgroup"
	CustomFieldRelatedObjectTypeIpamDotVLANgroup string = "ipam.VLANgroup"

	// CustomFieldRelatedObjectTypeIpamDotVRF captures enum value "ipam.VRF"
	CustomFieldRelatedObjectTypeIpamDotVRF string = "ipam.VRF"

	// CustomFieldRelatedObjectTypeTenancyDotContact captures enum value "tenancy.contact"
	CustomFieldRelatedObjectTypeTenancyDotContact string = "tenancy.contact"

	// CustomFieldRelatedObjectTypeTenancyDotContactassignment captures enum value "tenancy.contactassignment"
	CustomFieldRelatedObjectTypeTenancyDotContactassignment string = "tenancy.contactassignment"

	// CustomFieldRelatedObjectTypeTenancyDotContactgroup captures enum value "tenancy.contactgroup"
	CustomFieldRelatedObjectTypeTenancyDotContactgroup string = "tenancy.contactgroup"

	// CustomFieldRelatedObjectTypeTenancyDotContactrole captures enum value "tenancy.contactrole"
	CustomFieldRelatedObjectTypeTenancyDotContactrole string = "tenancy.contactrole"

	// CustomFieldRelatedObjectTypeTenancyDotTenant captures enum value "tenancy.tenant"
	CustomFieldRelatedObjectTypeTenancyDotTenant string = "tenancy.tenant"

	// CustomFieldRelatedObjectTypeTenancyDotTenantgroup captures enum value "tenancy.tenantgroup"
	CustomFieldRelatedObjectTypeTenancyDotTenantgroup string = "tenancy.tenantgroup"

	// CustomFieldRelatedObjectTypeVirtualizationDotCluster captures enum value "virtualization.cluster"
	CustomFieldRelatedObjectTypeVirtualizationDotCluster string = "virtualization.cluster"

	// CustomFieldRelatedObjectTypeVirtualizationDotClustergroup captures enum value "virtualization.clustergroup"
	CustomFieldRelatedObjectTypeVirtualizationDotClustergroup string = "virtualization.clustergroup"

	// CustomFieldRelatedObjectTypeVirtualizationDotClustertype captures enum value "virtualization.clustertype"
	CustomFieldRelatedObjectTypeVirtualizationDotClustertype string = "virtualization.clustertype"

	// CustomFieldRelatedObjectTypeVirtualizationDotInterface captures enum value "virtualization.interface"
	CustomFieldRelatedObjectTypeVirtualizationDotInterface string = "virtualization.interface"

	// CustomFieldRelatedObjectTypeVirtualizationDotVirtualmachine captures enum value "virtualization.virtualmachine"
	CustomFieldRelatedObjectTypeVirtualizationDotVirtualmachine string = "virtualization.virtualmachine"

	// CustomFieldRelatedObjectTypeWirelessDotWirelessLAN captures enum value "wireless.WirelessLAN"
	CustomFieldRelatedObjectTypeWirelessDotWirelessLAN string = "wireless.WirelessLAN"

	// CustomFieldRelatedObjectTypeWirelessDotWirelessLANGroup captures enum value "wireless.WirelessLANGroup"
	CustomFieldRelatedObjectTypeWirelessDotWirelessLANGroup string = "wireless.WirelessLANGroup"

	// CustomFieldRelatedObjectTypeWirelessDotWirelesslink captures enum value "wireless.wirelesslink"
	CustomFieldRelatedObjectTypeWirelessDotWirelesslink string = "wireless.wirelesslink"
)

// prop value enum
func (m *CustomField) validateRelatedObjectTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customFieldTypeRelatedObjectTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomField) validateRelatedObjectType(formats strfmt.Registry) error {
	if swag.IsZero(m.RelatedObjectType) { // not required
		return nil
	}

	// value enum
	if err := m.validateRelatedObjectTypeEnum("related_object_type", "body", m.RelatedObjectType); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateSearchWeight(formats strfmt.Registry) error {
	if swag.IsZero(m.SearchWeight) { // not required
		return nil
	}

	if err := validate.MinimumInt("search_weight", "body", *m.SearchWeight, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("search_weight", "body", *m.SearchWeight, 32767, false); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	if m.Type != nil {
		if err := m.Type.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("type")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) validateUIVisibility(formats strfmt.Registry) error {
	if swag.IsZero(m.UIVisibility) { // not required
		return nil
	}

	if m.UIVisibility != nil {
		if err := m.UIVisibility.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ui_visibility")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ui_visibility")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) validateURL(formats strfmt.Registry) error {
	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateValidationMaximum(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationMaximum) { // not required
		return nil
	}

	if err := validate.Minimum("validation_maximum", "body", *m.ValidationMaximum, -2.147483648e+09, false); err != nil {
		return err
	}

	if err := validate.Maximum("validation_maximum", "body", *m.ValidationMaximum, 2.147483647e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateValidationMinimum(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationMinimum) { // not required
		return nil
	}

	if err := validate.Minimum("validation_minimum", "body", *m.ValidationMinimum, -2.147483648e+09, false); err != nil {
		return err
	}

	if err := validate.Maximum("validation_minimum", "body", *m.ValidationMinimum, 2.147483647e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateValidationRegex(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationRegex) { // not required
		return nil
	}

	if err := validate.MaxLength("validation_regex", "body", m.ValidationRegex, 500); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) validateWeight(formats strfmt.Registry) error {
	if swag.IsZero(m.Weight) { // not required
		return nil
	}

	if err := validate.MinimumInt("weight", "body", *m.Weight, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("weight", "body", *m.Weight, 32767, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this custom field based on the context it is used
func (m *CustomField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChoiceSet(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCreated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDataType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDisplay(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFilterLogic(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastUpdated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUIVisibility(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateURL(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CustomField) contextValidateChoiceSet(ctx context.Context, formats strfmt.Registry) error {

	if m.ChoiceSet != nil {

		if swag.IsZero(m.ChoiceSet) { // not required
			return nil
		}

		if err := m.ChoiceSet.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("choice_set")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("choice_set")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) contextValidateCreated(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "created", "body", m.Created); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) contextValidateDataType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "data_type", "body", string(m.DataType)); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) contextValidateDisplay(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "display", "body", string(m.Display)); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) contextValidateFilterLogic(ctx context.Context, formats strfmt.Registry) error {

	if m.FilterLogic != nil {

		if swag.IsZero(m.FilterLogic) { // not required
			return nil
		}

		if err := m.FilterLogic.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filter_logic")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filter_logic")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) contextValidateLastUpdated(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "last_updated", "body", m.LastUpdated); err != nil {
		return err
	}

	return nil
}

func (m *CustomField) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if m.Type != nil {

		if err := m.Type.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("type")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("type")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) contextValidateUIVisibility(ctx context.Context, formats strfmt.Registry) error {

	if m.UIVisibility != nil {

		if swag.IsZero(m.UIVisibility) { // not required
			return nil
		}

		if err := m.UIVisibility.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ui_visibility")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ui_visibility")
			}
			return err
		}
	}

	return nil
}

func (m *CustomField) contextValidateURL(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "url", "body", strfmt.URI(m.URL)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CustomField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomField) UnmarshalBinary(b []byte) error {
	var res CustomField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CustomFieldFilterLogic Filter logic
//
// swagger:model CustomFieldFilterLogic
type CustomFieldFilterLogic struct {

	// label
	// Required: true
	// Enum: ["Disabled","Loose","Exact"]
	Label *string `json:"label"`

	// value
	// Required: true
	// Enum: ["disabled","loose","exact"]
	Value *string `json:"value"`
}

// Validate validates this custom field filter logic
func (m *CustomFieldFilterLogic) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var customFieldFilterLogicTypeLabelPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Disabled","Loose","Exact"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customFieldFilterLogicTypeLabelPropEnum = append(customFieldFilterLogicTypeLabelPropEnum, v)
	}
}

const (

	// CustomFieldFilterLogicLabelDisabled captures enum value "Disabled"
	CustomFieldFilterLogicLabelDisabled string = "Disabled"

	// CustomFieldFilterLogicLabelLoose captures enum value "Loose"
	CustomFieldFilterLogicLabelLoose string = "Loose"

	// CustomFieldFilterLogicLabelExact captures enum value "Exact"
	CustomFieldFilterLogicLabelExact string = "Exact"
)

// prop value enum
func (m *CustomFieldFilterLogic) validateLabelEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customFieldFilterLogicTypeLabelPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomFieldFilterLogic) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("filter_logic"+"."+"label", "body", m.Label); err != nil {
		return err
	}

	// value enum
	if err := m.validateLabelEnum("filter_logic"+"."+"label", "body", *m.Label); err != nil {
		return err
	}

	return nil
}

var customFieldFilterLogicTypeValuePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["disabled","loose","exact"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customFieldFilterLogicTypeValuePropEnum = append(customFieldFilterLogicTypeValuePropEnum, v)
	}
}

const (

	// CustomFieldFilterLogicValueDisabled captures enum value "disabled"
	CustomFieldFilterLogicValueDisabled string = "disabled"

	// CustomFieldFilterLogicValueLoose captures enum value "loose"
	CustomFieldFilterLogicValueLoose string = "loose"

	// CustomFieldFilterLogicValueExact captures enum value "exact"
	CustomFieldFilterLogicValueExact string = "exact"
)

// prop value enum
func (m *CustomFieldFilterLogic) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customFieldFilterLogicTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomFieldFilterLogic) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("filter_logic"+"."+"value", "body", m.Value); err != nil {
		return err
	}

	// value enum
	if err := m.validateValueEnum("filter_logic"+"."+"value", "body", *m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this custom field filter logic based on context it is used
func (m *CustomFieldFilterLogic) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomFieldFilterLogic) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomFieldFilterLogic) UnmarshalBinary(b []byte) error {
	var res CustomFieldFilterLogic
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CustomFieldType Type
//
// swagger:model CustomFieldType
type CustomFieldType struct {

	// label
	// Required: true
	// Enum: ["Text","Text (long)","Integer","Decimal","Boolean (true/false)","Date","URL","JSON","Selection","Multiple selection","Object","Multiple objects"]
	Label *string `json:"label"`

	// value
	// Required: true
	// Enum: ["text","longtext","integer","decimal","boolean","date","url","json","select","multiselect","object","multiobject"]
	Value *string `json:"value"`
}

// Validate validates this custom field type
func (m *CustomFieldType) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var customFieldTypeTypeLabelPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Text","Text (long)","Integer","Decimal","Boolean (true/false)","Date","URL","JSON","Selection","Multiple selection","Object","Multiple objects"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customFieldTypeTypeLabelPropEnum = append(customFieldTypeTypeLabelPropEnum, v)
	}
}

const (

	// CustomFieldTypeLabelText captures enum value "Text"
	CustomFieldTypeLabelText string = "Text"

	// CustomFieldTypeLabelTextLong captures enum value "Text (long)"
	CustomFieldTypeLabelTextLong string = "Text (long)"

	// CustomFieldTypeLabelInteger captures enum value "Integer"
	CustomFieldTypeLabelInteger string = "Integer"

	// CustomFieldTypeLabelDecimal captures enum value "Decimal"
	CustomFieldTypeLabelDecimal string = "Decimal"

	// CustomFieldTypeLabelBooleanTrueFalse captures enum value "Boolean (true/false)"
	CustomFieldTypeLabelBooleanTrueFalse string = "Boolean (true/false)"

	// CustomFieldTypeLabelDate captures enum value "Date"
	CustomFieldTypeLabelDate string = "Date"

	// CustomFieldTypeLabelURL captures enum value "URL"
	CustomFieldTypeLabelURL string = "URL"

	// CustomFieldTypeLabelJSON captures enum value "JSON"
	CustomFieldTypeLabelJSON string = "JSON"

	// CustomFieldTypeLabelSelection captures enum value "Selection"
	CustomFieldTypeLabelSelection string = "Selection"

	// CustomFieldTypeLabelMultipleSelection captures enum value "Multiple selection"
	CustomFieldTypeLabelMultipleSelection string = "Multiple selection"

	// CustomFieldTypeLabelObject captures enum value "Object"
	CustomFieldTypeLabelObject string = "Object"

	// CustomFieldTypeLabelMultipleObjects captures enum value "Multiple objects"
	CustomFieldTypeLabelMultipleObjects string = "Multiple objects"
)

// prop value enum
func (m *CustomFieldType) validateLabelEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customFieldTypeTypeLabelPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomFieldType) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("type"+"."+"label", "body", m.Label); err != nil {
		return err
	}

	// value enum
	if err := m.validateLabelEnum("type"+"."+"label", "body", *m.Label); err != nil {
		return err
	}

	return nil
}

var customFieldTypeTypeValuePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["text","longtext","integer","decimal","boolean","date","url","json","select","multiselect","object","multiobject"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customFieldTypeTypeValuePropEnum = append(customFieldTypeTypeValuePropEnum, v)
	}
}

const (

	// CustomFieldTypeValueText captures enum value "text"
	CustomFieldTypeValueText string = "text"

	// CustomFieldTypeValueLongtext captures enum value "longtext"
	CustomFieldTypeValueLongtext string = "longtext"

	// CustomFieldTypeValueInteger captures enum value "integer"
	CustomFieldTypeValueInteger string = "integer"

	// CustomFieldTypeValueDecimal captures enum value "decimal"
	CustomFieldTypeValueDecimal string = "decimal"

	// CustomFieldTypeValueBoolean captures enum value "boolean"
	CustomFieldTypeValueBoolean string = "boolean"

	// CustomFieldTypeValueDate captures enum value "date"
	CustomFieldTypeValueDate string = "date"

	// CustomFieldTypeValueURL captures enum value "url"
	CustomFieldTypeValueURL string = "url"

	// CustomFieldTypeValueJSON captures enum value "json"
	CustomFieldTypeValueJSON string = "json"

	// CustomFieldTypeValueSelect captures enum value "select"
	CustomFieldTypeValueSelect string = "select"

	// CustomFieldTypeValueMultiselect captures enum value "multiselect"
	CustomFieldTypeValueMultiselect string = "multiselect"

	// CustomFieldTypeValueObject captures enum value "object"
	CustomFieldTypeValueObject string = "object"

	// CustomFieldTypeValueMultiobject captures enum value "multiobject"
	CustomFieldTypeValueMultiobject string = "multiobject"
)

// prop value enum
func (m *CustomFieldType) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customFieldTypeTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomFieldType) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("type"+"."+"value", "body", m.Value); err != nil {
		return err
	}

	// value enum
	if err := m.validateValueEnum("type"+"."+"value", "body", *m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this custom field type based on context it is used
func (m *CustomFieldType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomFieldType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomFieldType) UnmarshalBinary(b []byte) error {
	var res CustomFieldType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CustomFieldUIVisibility Ui visibility
//
// swagger:model CustomFieldUIVisibility
type CustomFieldUIVisibility struct {

	// label
	// Required: true
	// Enum: ["Read/Write","Read-only","Hidden"]
	Label *string `json:"label"`

	// value
	// Required: true
	// Enum: ["read-write","read-only","hidden"]
	Value *string `json:"value"`
}

// Validate validates this custom field UI visibility
func (m *CustomFieldUIVisibility) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var customFieldUiVisibilityTypeLabelPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Read/Write","Read-only","Hidden"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customFieldUiVisibilityTypeLabelPropEnum = append(customFieldUiVisibilityTypeLabelPropEnum, v)
	}
}

const (

	// CustomFieldUIVisibilityLabelReadWrite captures enum value "Read/Write"
	CustomFieldUIVisibilityLabelReadWrite string = "Read/Write"

	// CustomFieldUIVisibilityLabelReadDashOnly captures enum value "Read-only"
	CustomFieldUIVisibilityLabelReadDashOnly string = "Read-only"

	// CustomFieldUIVisibilityLabelHidden captures enum value "Hidden"
	CustomFieldUIVisibilityLabelHidden string = "Hidden"
)

// prop value enum
func (m *CustomFieldUIVisibility) validateLabelEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customFieldUiVisibilityTypeLabelPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomFieldUIVisibility) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("ui_visibility"+"."+"label", "body", m.Label); err != nil {
		return err
	}

	// value enum
	if err := m.validateLabelEnum("ui_visibility"+"."+"label", "body", *m.Label); err != nil {
		return err
	}

	return nil
}

var customFieldUiVisibilityTypeValuePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["read-write","read-only","hidden"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customFieldUiVisibilityTypeValuePropEnum = append(customFieldUiVisibilityTypeValuePropEnum, v)
	}
}

const (

	// CustomFieldUIVisibilityValueReadDashWrite captures enum value "read-write"
	CustomFieldUIVisibilityValueReadDashWrite string = "read-write"

	// CustomFieldUIVisibilityValueReadDashOnly captures enum value "read-only"
	CustomFieldUIVisibilityValueReadDashOnly string = "read-only"

	// CustomFieldUIVisibilityValueHidden captures enum value "hidden"
	CustomFieldUIVisibilityValueHidden string = "hidden"
)

// prop value enum
func (m *CustomFieldUIVisibility) validateValueEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, customFieldUiVisibilityTypeValuePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CustomFieldUIVisibility) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("ui_visibility"+"."+"value", "body", m.Value); err != nil {
		return err
	}

	// value enum
	if err := m.validateValueEnum("ui_visibility"+"."+"value", "body", *m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this custom field UI visibility based on context it is used
func (m *CustomFieldUIVisibility) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomFieldUIVisibility) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomFieldUIVisibility) UnmarshalBinary(b []byte) error {
	var res CustomFieldUIVisibility
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
