// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeviceRenderConfig device render config
//
// swagger:model DeviceRenderConfig
type DeviceRenderConfig struct {

	// configtemplate
	Configtemplate *DeviceRenderConfigConfigtemplate `json:"configtemplate,omitempty"`

	// Content
	// Read Only: true
	Content string `json:"content,omitempty"`
}

// Validate validates this device render config
func (m *DeviceRenderConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConfigtemplate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceRenderConfig) validateConfigtemplate(formats strfmt.Registry) error {
	if swag.IsZero(m.Configtemplate) { // not required
		return nil
	}

	if m.Configtemplate != nil {
		if err := m.Configtemplate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configtemplate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("configtemplate")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this device render config based on the context it is used
func (m *DeviceRenderConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateConfigtemplate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateContent(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceRenderConfig) contextValidateConfigtemplate(ctx context.Context, formats strfmt.Registry) error {

	if m.Configtemplate != nil {

		if swag.IsZero(m.Configtemplate) { // not required
			return nil
		}

		if err := m.Configtemplate.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("configtemplate")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("configtemplate")
			}
			return err
		}
	}

	return nil
}

func (m *DeviceRenderConfig) contextValidateContent(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "content", "body", string(m.Content)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceRenderConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceRenderConfig) UnmarshalBinary(b []byte) error {
	var res DeviceRenderConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DeviceRenderConfigConfigtemplate Config template
//
// swagger:model DeviceRenderConfigConfigtemplate
type DeviceRenderConfigConfigtemplate struct {

	// Description
	// Read Only: true
	Description string `json:"description,omitempty"`

	// Display
	// Read Only: true
	Display string `json:"display,omitempty"`

	// ID
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Name
	// Read Only: true
	Name string `json:"name,omitempty"`

	// Url
	// Read Only: true
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`
}

// Validate validates this device render config configtemplate
func (m *DeviceRenderConfigConfigtemplate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceRenderConfigConfigtemplate) validateURL(formats strfmt.Registry) error {
	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("configtemplate"+"."+"url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this device render config configtemplate based on the context it is used
func (m *DeviceRenderConfigConfigtemplate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDescription(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDisplay(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateURL(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceRenderConfigConfigtemplate) contextValidateDescription(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "configtemplate"+"."+"description", "body", string(m.Description)); err != nil {
		return err
	}

	return nil
}

func (m *DeviceRenderConfigConfigtemplate) contextValidateDisplay(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "configtemplate"+"."+"display", "body", string(m.Display)); err != nil {
		return err
	}

	return nil
}

func (m *DeviceRenderConfigConfigtemplate) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "configtemplate"+"."+"id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *DeviceRenderConfigConfigtemplate) contextValidateName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "configtemplate"+"."+"name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

func (m *DeviceRenderConfigConfigtemplate) contextValidateURL(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "configtemplate"+"."+"url", "body", strfmt.URI(m.URL)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceRenderConfigConfigtemplate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceRenderConfigConfigtemplate) UnmarshalBinary(b []byte) error {
	var res DeviceRenderConfigConfigtemplate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
