// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WritableCustomField writable custom field
//
// swagger:model WritableCustomField
type WritableCustomField struct {

	// ChoiceSet
	ChoiceSet *int64 `json:"choice_set,omitempty"`

	// content types
	// Unique: true
	ContentTypes []string `json:"content_types,omitempty"`

	// Created
	// Read Only: true
	// Format: date-time
	Created *strfmt.DateTime `json:"created,omitempty"`

	// Data type
	// Read Only: true
	DataType string `json:"data_type,omitempty"`

	// Default
	//
	// Default value for the field (must be a JSON value). Encapsulate strings with double quotes (e.g. "Foo").
	Default interface{} `json:"default,omitempty"`

	// Description
	// Max Length: 200
	Description string `json:"description,omitempty"`

	// Display
	// Read Only: true
	Display string `json:"display,omitempty"`

	// Filter logic
	//
	// Loose matches any instance of a given string; exact matches the entire field.
	// Enum: ["disabled","loose","exact"]
	FilterLogic string `json:"filter_logic,omitempty"`

	// Group name
	//
	// Custom fields within the same group will be displayed together
	// Max Length: 50
	GroupName string `json:"group_name,omitempty"`

	// ID
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// Label
	//
	// Name of the field as displayed to users (if not provided, the field's name will be used)
	// Max Length: 50
	Label string `json:"label,omitempty"`

	// Last updated
	// Read Only: true
	// Format: date-time
	LastUpdated *strfmt.DateTime `json:"last_updated,omitempty"`

	// Name
	//
	// Internal field name
	// Required: true
	// Max Length: 50
	// Min Length: 1
	// Pattern: ^[a-z0-9_]+$
	Name *string `json:"name"`

	// Object type
	ObjectType string `json:"object_type,omitempty"`

	// object types
	// Unique: true
	ObjectTypes []string `json:"object_types,omitempty"`

	// Related object type
	// Enum: ["circuits.circuit","circuits.circuittermination","circuits.virtualcircuit","circuits.virtualcircuittermination","core.datasource","core.job","core.objectchange","dcim.cable","dcim.cablepath","dcim.cabletermination","dcim.consoleport","dcim.consoleporttemplate","dcim.consoleserverport","dcim.consoleserverporttemplate","dcim.device","dcim.devicebay","dcim.devicebaytemplate","dcim.devicerole","dcim.devicetype","dcim.frontport","dcim.frontporttemplate","dcim.interface","dcim.interfacetemplate","dcim.inventoryitem","dcim.inventoryitemrole","dcim.inventoryitemtemplate","dcim.location","dcim.manufacturer","dcim.module","dcim.modulebay","dcim.modulebaytemplate","dcim.moduletype","dcim.platform","dcim.powerfeed","dcim.poweroutlet","dcim.poweroutlettemplate","dcim.powerpanel","dcim.powerport","dcim.powerporttemplate","dcim.rack","dcim.rackreservation","dcim.rackrole","dcim.rearport","dcim.rearporttemplate","dcim.region","dcim.site","dcim.sitegroup","dcim.virtualchassis","extras.configcontext","extras.configrevision","extras.customfield","extras.customlink","extras.exporttemplate","extras.imageattachment","extras.jobresult","extras.journalentry","extras.report","extras.script","extras.tag","extras.taggeditem","extras.webhook","ipam.aggregate","ipam.ASN","ipam.FHRPgroup","ipam.FHRPgroupassignment","ipam.IPaddress","ipam.IPrange","ipam.L2VPN","ipam.L2VPNtermination","ipam.prefix","ipam.RIR","ipam.role","ipam.routetarget","ipam.service","ipam.servicetemplate","ipam.VLAN","ipam.VLANgroup","ipam.VRF","tenancy.contact","tenancy.contactassignment","tenancy.contactgroup","tenancy.contactrole","tenancy.tenant","tenancy.tenantgroup","virtualization.cluster","virtualization.clustergroup","virtualization.clustertype","virtualization.interface","virtualization.virtualmachine","wireless.WirelessLAN","wireless.WirelessLANGroup","wireless.wirelesslink"]
	RelatedObjectType string `json:"related_object_type,omitempty"`

	// Required
	//
	// If true, this field is required when creating new objects or editing an existing object.
	Required bool `json:"required"`

	// Search weight
	//
	// Weighting for search. Lower values are considered more important. Fields with a search weight of zero will be ignored.
	// Maximum: 32767
	// Minimum: 0
	SearchWeight *int64 `json:"search_weight,omitempty"`

	// Type
	//
	// The type of data this custom field holds
	// Enum: ["text","longtext","integer","decimal","boolean","date","url","json","select","multiselect","object","multiobject"]
	Type string `json:"type,omitempty"`

	// UI visibility
	//
	// Specifies the visibility of custom field in the UI
	// Enum: ["read-write","read-only","hidden"]
	UIVisibility string `json:"ui_visibility,omitempty"`

	// Url
	// Read Only: true
	// Format: uri
	URL strfmt.URI `json:"url,omitempty"`

	// Maximum value
	//
	// Maximum allowed value (for numeric fields)
	// Maximum: 2.147483647e+09
	// Minimum: -2.147483648e+09
	ValidationMaximum *float64 `json:"validation_maximum,omitempty"`

	// Minimum value
	//
	// Minimum allowed value (for numeric fields)
	// Maximum: 2.147483647e+09
	// Minimum: -2.147483648e+09
	ValidationMinimum *float64 `json:"validation_minimum,omitempty"`

	// Validation regex
	//
	// Regular expression to enforce on text field values. Use ^ and $ to force matching of entire string. For example, <code>^[A-Z]{3}$</code> will limit values to exactly three uppercase letters.
	// Max Length: 500
	ValidationRegex string `json:"validation_regex,omitempty"`

	// Display weight
	//
	// Fields with higher weights appear lower in a form.
	// Maximum: 32767
	// Minimum: 0
	Weight *int64 `json:"weight,omitempty"`
}

// Validate validates this writable custom field
func (m *WritableCustomField) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContentTypes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilterLogic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGroupName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObjectTypes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRelatedObjectType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSearchWeight(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUIVisibility(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationMaximum(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationMinimum(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValidationRegex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWeight(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WritableCustomField) validateContentTypes(formats strfmt.Registry) error {
	if swag.IsZero(m.ContentTypes) { // not required
		return nil
	}

	if err := validate.UniqueItems("content_types", "body", m.ContentTypes); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateCreated(formats strfmt.Registry) error {
	if swag.IsZero(m.Created) { // not required
		return nil
	}

	if err := validate.FormatOf("created", "body", "date-time", m.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateDescription(formats strfmt.Registry) error {
	if swag.IsZero(m.Description) { // not required
		return nil
	}

	if err := validate.MaxLength("description", "body", m.Description, 200); err != nil {
		return err
	}

	return nil
}

var writableCustomFieldTypeFilterLogicPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["disabled","loose","exact"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		writableCustomFieldTypeFilterLogicPropEnum = append(writableCustomFieldTypeFilterLogicPropEnum, v)
	}
}

const (

	// WritableCustomFieldFilterLogicDisabled captures enum value "disabled"
	WritableCustomFieldFilterLogicDisabled string = "disabled"

	// WritableCustomFieldFilterLogicLoose captures enum value "loose"
	WritableCustomFieldFilterLogicLoose string = "loose"

	// WritableCustomFieldFilterLogicExact captures enum value "exact"
	WritableCustomFieldFilterLogicExact string = "exact"
)

// prop value enum
func (m *WritableCustomField) validateFilterLogicEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, writableCustomFieldTypeFilterLogicPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WritableCustomField) validateFilterLogic(formats strfmt.Registry) error {
	if swag.IsZero(m.FilterLogic) { // not required
		return nil
	}

	// value enum
	if err := m.validateFilterLogicEnum("filter_logic", "body", m.FilterLogic); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateGroupName(formats strfmt.Registry) error {
	if swag.IsZero(m.GroupName) { // not required
		return nil
	}

	if err := validate.MaxLength("group_name", "body", m.GroupName, 50); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateLabel(formats strfmt.Registry) error {
	if swag.IsZero(m.Label) { // not required
		return nil
	}

	if err := validate.MaxLength("label", "body", m.Label, 50); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateLastUpdated(formats strfmt.Registry) error {
	if swag.IsZero(m.LastUpdated) { // not required
		return nil
	}

	if err := validate.FormatOf("last_updated", "body", "date-time", m.LastUpdated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", *m.Name, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("name", "body", *m.Name, 50); err != nil {
		return err
	}

	if err := validate.Pattern("name", "body", *m.Name, `^[a-z0-9_]+$`); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateObjectTypes(formats strfmt.Registry) error {
	if swag.IsZero(m.ObjectTypes) { // not required
		return nil
	}

	if err := validate.UniqueItems("object_types", "body", m.ObjectTypes); err != nil {
		return err
	}

	return nil
}

var writableCustomFieldTypeRelatedObjectTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["circuits.circuit","circuits.circuittermination","circuits.virtualcircuit","circuits.virtualcircuittermination","core.datasource","core.job","core.objectchange","dcim.cable","dcim.cablepath","dcim.cabletermination","dcim.consoleport","dcim.consoleporttemplate","dcim.consoleserverport","dcim.consoleserverporttemplate","dcim.device","dcim.devicebay","dcim.devicebaytemplate","dcim.devicerole","dcim.devicetype","dcim.frontport","dcim.frontporttemplate","dcim.interface","dcim.interfacetemplate","dcim.inventoryitem","dcim.inventoryitemrole","dcim.inventoryitemtemplate","dcim.location","dcim.manufacturer","dcim.module","dcim.modulebay","dcim.modulebaytemplate","dcim.moduletype","dcim.platform","dcim.powerfeed","dcim.poweroutlet","dcim.poweroutlettemplate","dcim.powerpanel","dcim.powerport","dcim.powerporttemplate","dcim.rack","dcim.rackreservation","dcim.rackrole","dcim.rearport","dcim.rearporttemplate","dcim.region","dcim.site","dcim.sitegroup","dcim.virtualchassis","extras.configcontext","extras.configrevision","extras.customfield","extras.customlink","extras.exporttemplate","extras.imageattachment","extras.jobresult","extras.journalentry","extras.report","extras.script","extras.tag","extras.taggeditem","extras.webhook","ipam.aggregate","ipam.ASN","ipam.FHRPgroup","ipam.FHRPgroupassignment","ipam.IPaddress","ipam.IPrange","ipam.L2VPN","ipam.L2VPNtermination","ipam.prefix","ipam.RIR","ipam.role","ipam.routetarget","ipam.service","ipam.servicetemplate","ipam.VLAN","ipam.VLANgroup","ipam.VRF","tenancy.contact","tenancy.contactassignment","tenancy.contactgroup","tenancy.contactrole","tenancy.tenant","tenancy.tenantgroup","virtualization.cluster","virtualization.clustergroup","virtualization.clustertype","virtualization.interface","virtualization.virtualmachine","wireless.WirelessLAN","wireless.WirelessLANGroup","wireless.wirelesslink"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		writableCustomFieldTypeRelatedObjectTypePropEnum = append(writableCustomFieldTypeRelatedObjectTypePropEnum, v)
	}
}

const (

	// WritableCustomFieldRelatedObjectTypeCircuitsDotCircuit captures enum value "circuits.circuit"
	WritableCustomFieldRelatedObjectTypeCircuitsDotCircuit string = "circuits.circuit"

	// WritableCustomFieldRelatedObjectTypeCircuitsDotCircuittermination captures enum value "circuits.circuittermination"
	WritableCustomFieldRelatedObjectTypeCircuitsDotCircuittermination string = "circuits.circuittermination"

	// WritableCustomFieldRelatedObjectTypeCircuitsDotVirtualcircuit captures enum value "circuits.virtualcircuit"
	WritableCustomFieldRelatedObjectTypeCircuitsDotVirtualcircuit string = "circuits.virtualcircuit"

	// WritableCustomFieldRelatedObjectTypeCircuitsDotVirtualcircuittermination captures enum value "circuits.virtualcircuittermination"
	WritableCustomFieldRelatedObjectTypeCircuitsDotVirtualcircuittermination string = "circuits.virtualcircuittermination"

	// WritableCustomFieldRelatedObjectTypeCoreDotDatasource captures enum value "core.datasource"
	WritableCustomFieldRelatedObjectTypeCoreDotDatasource string = "core.datasource"

	// WritableCustomFieldRelatedObjectTypeCoreDotJob captures enum value "core.job"
	WritableCustomFieldRelatedObjectTypeCoreDotJob string = "core.job"

	// WritableCustomFieldRelatedObjectTypeCoreDotObjectchange captures enum value "core.objectchange"
	WritableCustomFieldRelatedObjectTypeCoreDotObjectchange string = "core.objectchange"

	// WritableCustomFieldRelatedObjectTypeDcimDotCable captures enum value "dcim.cable"
	WritableCustomFieldRelatedObjectTypeDcimDotCable string = "dcim.cable"

	// WritableCustomFieldRelatedObjectTypeDcimDotCablepath captures enum value "dcim.cablepath"
	WritableCustomFieldRelatedObjectTypeDcimDotCablepath string = "dcim.cablepath"

	// WritableCustomFieldRelatedObjectTypeDcimDotCabletermination captures enum value "dcim.cabletermination"
	WritableCustomFieldRelatedObjectTypeDcimDotCabletermination string = "dcim.cabletermination"

	// WritableCustomFieldRelatedObjectTypeDcimDotConsoleport captures enum value "dcim.consoleport"
	WritableCustomFieldRelatedObjectTypeDcimDotConsoleport string = "dcim.consoleport"

	// WritableCustomFieldRelatedObjectTypeDcimDotConsoleporttemplate captures enum value "dcim.consoleporttemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotConsoleporttemplate string = "dcim.consoleporttemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotConsoleserverport captures enum value "dcim.consoleserverport"
	WritableCustomFieldRelatedObjectTypeDcimDotConsoleserverport string = "dcim.consoleserverport"

	// WritableCustomFieldRelatedObjectTypeDcimDotConsoleserverporttemplate captures enum value "dcim.consoleserverporttemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotConsoleserverporttemplate string = "dcim.consoleserverporttemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotDevice captures enum value "dcim.device"
	WritableCustomFieldRelatedObjectTypeDcimDotDevice string = "dcim.device"

	// WritableCustomFieldRelatedObjectTypeDcimDotDevicebay captures enum value "dcim.devicebay"
	WritableCustomFieldRelatedObjectTypeDcimDotDevicebay string = "dcim.devicebay"

	// WritableCustomFieldRelatedObjectTypeDcimDotDevicebaytemplate captures enum value "dcim.devicebaytemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotDevicebaytemplate string = "dcim.devicebaytemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotDevicerole captures enum value "dcim.devicerole"
	WritableCustomFieldRelatedObjectTypeDcimDotDevicerole string = "dcim.devicerole"

	// WritableCustomFieldRelatedObjectTypeDcimDotDevicetype captures enum value "dcim.devicetype"
	WritableCustomFieldRelatedObjectTypeDcimDotDevicetype string = "dcim.devicetype"

	// WritableCustomFieldRelatedObjectTypeDcimDotFrontport captures enum value "dcim.frontport"
	WritableCustomFieldRelatedObjectTypeDcimDotFrontport string = "dcim.frontport"

	// WritableCustomFieldRelatedObjectTypeDcimDotFrontporttemplate captures enum value "dcim.frontporttemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotFrontporttemplate string = "dcim.frontporttemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotInterface captures enum value "dcim.interface"
	WritableCustomFieldRelatedObjectTypeDcimDotInterface string = "dcim.interface"

	// WritableCustomFieldRelatedObjectTypeDcimDotInterfacetemplate captures enum value "dcim.interfacetemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotInterfacetemplate string = "dcim.interfacetemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotInventoryitem captures enum value "dcim.inventoryitem"
	WritableCustomFieldRelatedObjectTypeDcimDotInventoryitem string = "dcim.inventoryitem"

	// WritableCustomFieldRelatedObjectTypeDcimDotInventoryitemrole captures enum value "dcim.inventoryitemrole"
	WritableCustomFieldRelatedObjectTypeDcimDotInventoryitemrole string = "dcim.inventoryitemrole"

	// WritableCustomFieldRelatedObjectTypeDcimDotInventoryitemtemplate captures enum value "dcim.inventoryitemtemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotInventoryitemtemplate string = "dcim.inventoryitemtemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotLocation captures enum value "dcim.location"
	WritableCustomFieldRelatedObjectTypeDcimDotLocation string = "dcim.location"

	// WritableCustomFieldRelatedObjectTypeDcimDotManufacturer captures enum value "dcim.manufacturer"
	WritableCustomFieldRelatedObjectTypeDcimDotManufacturer string = "dcim.manufacturer"

	// WritableCustomFieldRelatedObjectTypeDcimDotModule captures enum value "dcim.module"
	WritableCustomFieldRelatedObjectTypeDcimDotModule string = "dcim.module"

	// WritableCustomFieldRelatedObjectTypeDcimDotModulebay captures enum value "dcim.modulebay"
	WritableCustomFieldRelatedObjectTypeDcimDotModulebay string = "dcim.modulebay"

	// WritableCustomFieldRelatedObjectTypeDcimDotModulebaytemplate captures enum value "dcim.modulebaytemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotModulebaytemplate string = "dcim.modulebaytemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotModuletype captures enum value "dcim.moduletype"
	WritableCustomFieldRelatedObjectTypeDcimDotModuletype string = "dcim.moduletype"

	// WritableCustomFieldRelatedObjectTypeDcimDotPlatform captures enum value "dcim.platform"
	WritableCustomFieldRelatedObjectTypeDcimDotPlatform string = "dcim.platform"

	// WritableCustomFieldRelatedObjectTypeDcimDotPowerfeed captures enum value "dcim.powerfeed"
	WritableCustomFieldRelatedObjectTypeDcimDotPowerfeed string = "dcim.powerfeed"

	// WritableCustomFieldRelatedObjectTypeDcimDotPoweroutlet captures enum value "dcim.poweroutlet"
	WritableCustomFieldRelatedObjectTypeDcimDotPoweroutlet string = "dcim.poweroutlet"

	// WritableCustomFieldRelatedObjectTypeDcimDotPoweroutlettemplate captures enum value "dcim.poweroutlettemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotPoweroutlettemplate string = "dcim.poweroutlettemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotPowerpanel captures enum value "dcim.powerpanel"
	WritableCustomFieldRelatedObjectTypeDcimDotPowerpanel string = "dcim.powerpanel"

	// WritableCustomFieldRelatedObjectTypeDcimDotPowerport captures enum value "dcim.powerport"
	WritableCustomFieldRelatedObjectTypeDcimDotPowerport string = "dcim.powerport"

	// WritableCustomFieldRelatedObjectTypeDcimDotPowerporttemplate captures enum value "dcim.powerporttemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotPowerporttemplate string = "dcim.powerporttemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotRack captures enum value "dcim.rack"
	WritableCustomFieldRelatedObjectTypeDcimDotRack string = "dcim.rack"

	// WritableCustomFieldRelatedObjectTypeDcimDotRackreservation captures enum value "dcim.rackreservation"
	WritableCustomFieldRelatedObjectTypeDcimDotRackreservation string = "dcim.rackreservation"

	// WritableCustomFieldRelatedObjectTypeDcimDotRackrole captures enum value "dcim.rackrole"
	WritableCustomFieldRelatedObjectTypeDcimDotRackrole string = "dcim.rackrole"

	// WritableCustomFieldRelatedObjectTypeDcimDotRearport captures enum value "dcim.rearport"
	WritableCustomFieldRelatedObjectTypeDcimDotRearport string = "dcim.rearport"

	// WritableCustomFieldRelatedObjectTypeDcimDotRearporttemplate captures enum value "dcim.rearporttemplate"
	WritableCustomFieldRelatedObjectTypeDcimDotRearporttemplate string = "dcim.rearporttemplate"

	// WritableCustomFieldRelatedObjectTypeDcimDotRegion captures enum value "dcim.region"
	WritableCustomFieldRelatedObjectTypeDcimDotRegion string = "dcim.region"

	// WritableCustomFieldRelatedObjectTypeDcimDotSite captures enum value "dcim.site"
	WritableCustomFieldRelatedObjectTypeDcimDotSite string = "dcim.site"

	// WritableCustomFieldRelatedObjectTypeDcimDotSitegroup captures enum value "dcim.sitegroup"
	WritableCustomFieldRelatedObjectTypeDcimDotSitegroup string = "dcim.sitegroup"

	// WritableCustomFieldRelatedObjectTypeDcimDotVirtualchassis captures enum value "dcim.virtualchassis"
	WritableCustomFieldRelatedObjectTypeDcimDotVirtualchassis string = "dcim.virtualchassis"

	// WritableCustomFieldRelatedObjectTypeExtrasDotConfigcontext captures enum value "extras.configcontext"
	WritableCustomFieldRelatedObjectTypeExtrasDotConfigcontext string = "extras.configcontext"

	// WritableCustomFieldRelatedObjectTypeExtrasDotConfigrevision captures enum value "extras.configrevision"
	WritableCustomFieldRelatedObjectTypeExtrasDotConfigrevision string = "extras.configrevision"

	// WritableCustomFieldRelatedObjectTypeExtrasDotCustomfield captures enum value "extras.customfield"
	WritableCustomFieldRelatedObjectTypeExtrasDotCustomfield string = "extras.customfield"

	// WritableCustomFieldRelatedObjectTypeExtrasDotCustomlink captures enum value "extras.customlink"
	WritableCustomFieldRelatedObjectTypeExtrasDotCustomlink string = "extras.customlink"

	// WritableCustomFieldRelatedObjectTypeExtrasDotExporttemplate captures enum value "extras.exporttemplate"
	WritableCustomFieldRelatedObjectTypeExtrasDotExporttemplate string = "extras.exporttemplate"

	// WritableCustomFieldRelatedObjectTypeExtrasDotImageattachment captures enum value "extras.imageattachment"
	WritableCustomFieldRelatedObjectTypeExtrasDotImageattachment string = "extras.imageattachment"

	// WritableCustomFieldRelatedObjectTypeExtrasDotJobresult captures enum value "extras.jobresult"
	WritableCustomFieldRelatedObjectTypeExtrasDotJobresult string = "extras.jobresult"

	// WritableCustomFieldRelatedObjectTypeExtrasDotJournalentry captures enum value "extras.journalentry"
	WritableCustomFieldRelatedObjectTypeExtrasDotJournalentry string = "extras.journalentry"

	// WritableCustomFieldRelatedObjectTypeExtrasDotReport captures enum value "extras.report"
	WritableCustomFieldRelatedObjectTypeExtrasDotReport string = "extras.report"

	// WritableCustomFieldRelatedObjectTypeExtrasDotScript captures enum value "extras.script"
	WritableCustomFieldRelatedObjectTypeExtrasDotScript string = "extras.script"

	// WritableCustomFieldRelatedObjectTypeExtrasDotTag captures enum value "extras.tag"
	WritableCustomFieldRelatedObjectTypeExtrasDotTag string = "extras.tag"

	// WritableCustomFieldRelatedObjectTypeExtrasDotTaggeditem captures enum value "extras.taggeditem"
	WritableCustomFieldRelatedObjectTypeExtrasDotTaggeditem string = "extras.taggeditem"

	// WritableCustomFieldRelatedObjectTypeExtrasDotWebhook captures enum value "extras.webhook"
	WritableCustomFieldRelatedObjectTypeExtrasDotWebhook string = "extras.webhook"

	// WritableCustomFieldRelatedObjectTypeIpamDotAggregate captures enum value "ipam.aggregate"
	WritableCustomFieldRelatedObjectTypeIpamDotAggregate string = "ipam.aggregate"

	// WritableCustomFieldRelatedObjectTypeIpamDotASN captures enum value "ipam.ASN"
	WritableCustomFieldRelatedObjectTypeIpamDotASN string = "ipam.ASN"

	// WritableCustomFieldRelatedObjectTypeIpamDotFHRPgroup captures enum value "ipam.FHRPgroup"
	WritableCustomFieldRelatedObjectTypeIpamDotFHRPgroup string = "ipam.FHRPgroup"

	// WritableCustomFieldRelatedObjectTypeIpamDotFHRPgroupassignment captures enum value "ipam.FHRPgroupassignment"
	WritableCustomFieldRelatedObjectTypeIpamDotFHRPgroupassignment string = "ipam.FHRPgroupassignment"

	// WritableCustomFieldRelatedObjectTypeIpamDotIPaddress captures enum value "ipam.IPaddress"
	WritableCustomFieldRelatedObjectTypeIpamDotIPaddress string = "ipam.IPaddress"

	// WritableCustomFieldRelatedObjectTypeIpamDotIPrange captures enum value "ipam.IPrange"
	WritableCustomFieldRelatedObjectTypeIpamDotIPrange string = "ipam.IPrange"

	// WritableCustomFieldRelatedObjectTypeIpamDotL2VPN captures enum value "ipam.L2VPN"
	WritableCustomFieldRelatedObjectTypeIpamDotL2VPN string = "ipam.L2VPN"

	// WritableCustomFieldRelatedObjectTypeIpamDotL2VPNtermination captures enum value "ipam.L2VPNtermination"
	WritableCustomFieldRelatedObjectTypeIpamDotL2VPNtermination string = "ipam.L2VPNtermination"

	// WritableCustomFieldRelatedObjectTypeIpamDotPrefix captures enum value "ipam.prefix"
	WritableCustomFieldRelatedObjectTypeIpamDotPrefix string = "ipam.prefix"

	// WritableCustomFieldRelatedObjectTypeIpamDotRIR captures enum value "ipam.RIR"
	WritableCustomFieldRelatedObjectTypeIpamDotRIR string = "ipam.RIR"

	// WritableCustomFieldRelatedObjectTypeIpamDotRole captures enum value "ipam.role"
	WritableCustomFieldRelatedObjectTypeIpamDotRole string = "ipam.role"

	// WritableCustomFieldRelatedObjectTypeIpamDotRoutetarget captures enum value "ipam.routetarget"
	WritableCustomFieldRelatedObjectTypeIpamDotRoutetarget string = "ipam.routetarget"

	// WritableCustomFieldRelatedObjectTypeIpamDotService captures enum value "ipam.service"
	WritableCustomFieldRelatedObjectTypeIpamDotService string = "ipam.service"

	// WritableCustomFieldRelatedObjectTypeIpamDotServicetemplate captures enum value "ipam.servicetemplate"
	WritableCustomFieldRelatedObjectTypeIpamDotServicetemplate string = "ipam.servicetemplate"

	// WritableCustomFieldRelatedObjectTypeIpamDotVLAN captures enum value "ipam.VLAN"
	WritableCustomFieldRelatedObjectTypeIpamDotVLAN string = "ipam.VLAN"

	// WritableCustomFieldRelatedObjectTypeIpamDotVLANgroup captures enum value "ipam.VLANgroup"
	WritableCustomFieldRelatedObjectTypeIpamDotVLANgroup string = "ipam.VLANgroup"

	// WritableCustomFieldRelatedObjectTypeIpamDotVRF captures enum value "ipam.VRF"
	WritableCustomFieldRelatedObjectTypeIpamDotVRF string = "ipam.VRF"

	// WritableCustomFieldRelatedObjectTypeTenancyDotContact captures enum value "tenancy.contact"
	WritableCustomFieldRelatedObjectTypeTenancyDotContact string = "tenancy.contact"

	// WritableCustomFieldRelatedObjectTypeTenancyDotContactassignment captures enum value "tenancy.contactassignment"
	WritableCustomFieldRelatedObjectTypeTenancyDotContactassignment string = "tenancy.contactassignment"

	// WritableCustomFieldRelatedObjectTypeTenancyDotContactgroup captures enum value "tenancy.contactgroup"
	WritableCustomFieldRelatedObjectTypeTenancyDotContactgroup string = "tenancy.contactgroup"

	// WritableCustomFieldRelatedObjectTypeTenancyDotContactrole captures enum value "tenancy.contactrole"
	WritableCustomFieldRelatedObjectTypeTenancyDotContactrole string = "tenancy.contactrole"

	// WritableCustomFieldRelatedObjectTypeTenancyDotTenant captures enum value "tenancy.tenant"
	WritableCustomFieldRelatedObjectTypeTenancyDotTenant string = "tenancy.tenant"

	// WritableCustomFieldRelatedObjectTypeTenancyDotTenantgroup captures enum value "tenancy.tenantgroup"
	WritableCustomFieldRelatedObjectTypeTenancyDotTenantgroup string = "tenancy.tenantgroup"

	// WritableCustomFieldRelatedObjectTypeVirtualizationDotCluster captures enum value "virtualization.cluster"
	WritableCustomFieldRelatedObjectTypeVirtualizationDotCluster string = "virtualization.cluster"

	// WritableCustomFieldRelatedObjectTypeVirtualizationDotClustergroup captures enum value "virtualization.clustergroup"
	WritableCustomFieldRelatedObjectTypeVirtualizationDotClustergroup string = "virtualization.clustergroup"

	// WritableCustomFieldRelatedObjectTypeVirtualizationDotClustertype captures enum value "virtualization.clustertype"
	WritableCustomFieldRelatedObjectTypeVirtualizationDotClustertype string = "virtualization.clustertype"

	// WritableCustomFieldRelatedObjectTypeVirtualizationDotInterface captures enum value "virtualization.interface"
	WritableCustomFieldRelatedObjectTypeVirtualizationDotInterface string = "virtualization.interface"

	// WritableCustomFieldRelatedObjectTypeVirtualizationDotVirtualmachine captures enum value "virtualization.virtualmachine"
	WritableCustomFieldRelatedObjectTypeVirtualizationDotVirtualmachine string = "virtualization.virtualmachine"

	// WritableCustomFieldRelatedObjectTypeWirelessDotWirelessLAN captures enum value "wireless.WirelessLAN"
	WritableCustomFieldRelatedObjectTypeWirelessDotWirelessLAN string = "wireless.WirelessLAN"

	// WritableCustomFieldRelatedObjectTypeWirelessDotWirelessLANGroup captures enum value "wireless.WirelessLANGroup"
	WritableCustomFieldRelatedObjectTypeWirelessDotWirelessLANGroup string = "wireless.WirelessLANGroup"

	// WritableCustomFieldRelatedObjectTypeWirelessDotWirelesslink captures enum value "wireless.wirelesslink"
	WritableCustomFieldRelatedObjectTypeWirelessDotWirelesslink string = "wireless.wirelesslink"
)

// prop value enum
func (m *WritableCustomField) validateRelatedObjectTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, writableCustomFieldTypeRelatedObjectTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WritableCustomField) validateRelatedObjectType(formats strfmt.Registry) error {
	if swag.IsZero(m.RelatedObjectType) { // not required
		return nil
	}

	// value enum
	if err := m.validateRelatedObjectTypeEnum("related_object_type", "body", m.RelatedObjectType); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateSearchWeight(formats strfmt.Registry) error {
	if swag.IsZero(m.SearchWeight) { // not required
		return nil
	}

	if err := validate.MinimumInt("search_weight", "body", *m.SearchWeight, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("search_weight", "body", *m.SearchWeight, 32767, false); err != nil {
		return err
	}

	return nil
}

var writableCustomFieldTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["text","longtext","integer","decimal","boolean","date","url","json","select","multiselect","object","multiobject"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		writableCustomFieldTypeTypePropEnum = append(writableCustomFieldTypeTypePropEnum, v)
	}
}

const (

	// WritableCustomFieldTypeText captures enum value "text"
	WritableCustomFieldTypeText string = "text"

	// WritableCustomFieldTypeLongtext captures enum value "longtext"
	WritableCustomFieldTypeLongtext string = "longtext"

	// WritableCustomFieldTypeInteger captures enum value "integer"
	WritableCustomFieldTypeInteger string = "integer"

	// WritableCustomFieldTypeDecimal captures enum value "decimal"
	WritableCustomFieldTypeDecimal string = "decimal"

	// WritableCustomFieldTypeBoolean captures enum value "boolean"
	WritableCustomFieldTypeBoolean string = "boolean"

	// WritableCustomFieldTypeDate captures enum value "date"
	WritableCustomFieldTypeDate string = "date"

	// WritableCustomFieldTypeURL captures enum value "url"
	WritableCustomFieldTypeURL string = "url"

	// WritableCustomFieldTypeJSON captures enum value "json"
	WritableCustomFieldTypeJSON string = "json"

	// WritableCustomFieldTypeSelect captures enum value "select"
	WritableCustomFieldTypeSelect string = "select"

	// WritableCustomFieldTypeMultiselect captures enum value "multiselect"
	WritableCustomFieldTypeMultiselect string = "multiselect"

	// WritableCustomFieldTypeObject captures enum value "object"
	WritableCustomFieldTypeObject string = "object"

	// WritableCustomFieldTypeMultiobject captures enum value "multiobject"
	WritableCustomFieldTypeMultiobject string = "multiobject"
)

// prop value enum
func (m *WritableCustomField) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, writableCustomFieldTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WritableCustomField) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

var writableCustomFieldTypeUIVisibilityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["read-write","read-only","hidden"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		writableCustomFieldTypeUIVisibilityPropEnum = append(writableCustomFieldTypeUIVisibilityPropEnum, v)
	}
}

const (

	// WritableCustomFieldUIVisibilityReadDashWrite captures enum value "read-write"
	WritableCustomFieldUIVisibilityReadDashWrite string = "read-write"

	// WritableCustomFieldUIVisibilityReadDashOnly captures enum value "read-only"
	WritableCustomFieldUIVisibilityReadDashOnly string = "read-only"

	// WritableCustomFieldUIVisibilityHidden captures enum value "hidden"
	WritableCustomFieldUIVisibilityHidden string = "hidden"
)

// prop value enum
func (m *WritableCustomField) validateUIVisibilityEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, writableCustomFieldTypeUIVisibilityPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *WritableCustomField) validateUIVisibility(formats strfmt.Registry) error {
	if swag.IsZero(m.UIVisibility) { // not required
		return nil
	}

	// value enum
	if err := m.validateUIVisibilityEnum("ui_visibility", "body", m.UIVisibility); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateURL(formats strfmt.Registry) error {
	if swag.IsZero(m.URL) { // not required
		return nil
	}

	if err := validate.FormatOf("url", "body", "uri", m.URL.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateValidationMaximum(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationMaximum) { // not required
		return nil
	}

	if err := validate.Minimum("validation_maximum", "body", *m.ValidationMaximum, -2.147483648e+09, false); err != nil {
		return err
	}

	if err := validate.Maximum("validation_maximum", "body", *m.ValidationMaximum, 2.147483647e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateValidationMinimum(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationMinimum) { // not required
		return nil
	}

	if err := validate.Minimum("validation_minimum", "body", *m.ValidationMinimum, -2.147483648e+09, false); err != nil {
		return err
	}

	if err := validate.Maximum("validation_minimum", "body", *m.ValidationMinimum, 2.147483647e+09, false); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateValidationRegex(formats strfmt.Registry) error {
	if swag.IsZero(m.ValidationRegex) { // not required
		return nil
	}

	if err := validate.MaxLength("validation_regex", "body", m.ValidationRegex, 500); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) validateWeight(formats strfmt.Registry) error {
	if swag.IsZero(m.Weight) { // not required
		return nil
	}

	if err := validate.MinimumInt("weight", "body", *m.Weight, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("weight", "body", *m.Weight, 32767, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this writable custom field based on the context it is used
func (m *WritableCustomField) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDataType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDisplay(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastUpdated(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateURL(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WritableCustomField) contextValidateCreated(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "created", "body", m.Created); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) contextValidateDataType(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "data_type", "body", string(m.DataType)); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) contextValidateDisplay(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "display", "body", string(m.Display)); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", int64(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) contextValidateLastUpdated(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "last_updated", "body", m.LastUpdated); err != nil {
		return err
	}

	return nil
}

func (m *WritableCustomField) contextValidateURL(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "url", "body", strfmt.URI(m.URL)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WritableCustomField) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WritableCustomField) UnmarshalBinary(b []byte) error {
	var res WritableCustomField
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
