// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimMacAddressesDeleteReader is a Reader for the DcimMacAddressesDelete structure.
type DcimMacAddressesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimMacAddressesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimMacAddressesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimMacAddressesDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimMacAddressesDeleteNoContent creates a DcimMacAddressesDeleteNoContent with default headers values
func NewDcimMacAddressesDeleteNoContent() *DcimMacAddressesDeleteNoContent {
	return &DcimMacAddressesDeleteNoContent{}
}

/*
DcimMacAddressesDeleteNoContent describes a response with status code 204, with default header values.

DcimMacAddressesDeleteNoContent dcim mac addresses delete no content
*/
type DcimMacAddressesDeleteNoContent struct {
}

// IsSuccess returns true when this dcim mac addresses delete no content response has a 2xx status code
func (o *DcimMacAddressesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim mac addresses delete no content response has a 3xx status code
func (o *DcimMacAddressesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim mac addresses delete no content response has a 4xx status code
func (o *DcimMacAddressesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim mac addresses delete no content response has a 5xx status code
func (o *DcimMacAddressesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim mac addresses delete no content response a status code equal to that given
func (o *DcimMacAddressesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim mac addresses delete no content response
func (o *DcimMacAddressesDeleteNoContent) Code() int {
	return 204
}

func (o *DcimMacAddressesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/mac-addresses/{id}/][%d] dcimMacAddressesDeleteNoContent", 204)
}

func (o *DcimMacAddressesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/mac-addresses/{id}/][%d] dcimMacAddressesDeleteNoContent", 204)
}

func (o *DcimMacAddressesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDcimMacAddressesDeleteDefault creates a DcimMacAddressesDeleteDefault with default headers values
func NewDcimMacAddressesDeleteDefault(code int) *DcimMacAddressesDeleteDefault {
	return &DcimMacAddressesDeleteDefault{
		_statusCode: code,
	}
}

/*
DcimMacAddressesDeleteDefault describes a response with status code -1, with default header values.

DcimMacAddressesDeleteDefault dcim mac addresses delete default
*/
type DcimMacAddressesDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this dcim mac addresses delete default response has a 2xx status code
func (o *DcimMacAddressesDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim mac addresses delete default response has a 3xx status code
func (o *DcimMacAddressesDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim mac addresses delete default response has a 4xx status code
func (o *DcimMacAddressesDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim mac addresses delete default response has a 5xx status code
func (o *DcimMacAddressesDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim mac addresses delete default response a status code equal to that given
func (o *DcimMacAddressesDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim mac addresses delete default response
func (o *DcimMacAddressesDeleteDefault) Code() int {
	return o._statusCode
}

func (o *DcimMacAddressesDeleteDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/mac-addresses/{id}/][%d] dcim_mac-addresses_delete default %s", o._statusCode, payload)
}

func (o *DcimMacAddressesDeleteDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/mac-addresses/{id}/][%d] dcim_mac-addresses_delete default %s", o._statusCode, payload)
}

func (o *DcimMacAddressesDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimMacAddressesDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
