// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DcimRackTypesDeleteReader is a Reader for the DcimRackTypesDelete structure.
type DcimRackTypesDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackTypesDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDcimRackTypesDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimRackTypesDeleteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimRackTypesDeleteNoContent creates a DcimRackTypesDeleteNoContent with default headers values
func NewDcimRackTypesDeleteNoContent() *DcimRackTypesDeleteNoContent {
	return &DcimRackTypesDeleteNoContent{}
}

/*
DcimRackTypesDeleteNoContent describes a response with status code 204, with default header values.

No response body
*/
type DcimRackTypesDeleteNoContent struct {
}

// IsSuccess returns true when this dcim rack types delete no content response has a 2xx status code
func (o *DcimRackTypesDeleteNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim rack types delete no content response has a 3xx status code
func (o *DcimRackTypesDeleteNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim rack types delete no content response has a 4xx status code
func (o *DcimRackTypesDeleteNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim rack types delete no content response has a 5xx status code
func (o *DcimRackTypesDeleteNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim rack types delete no content response a status code equal to that given
func (o *DcimRackTypesDeleteNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the dcim rack types delete no content response
func (o *DcimRackTypesDeleteNoContent) Code() int {
	return 204
}

func (o *DcimRackTypesDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcimRackTypesDeleteNoContent", 204)
}

func (o *DcimRackTypesDeleteNoContent) String() string {
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcimRackTypesDeleteNoContent", 204)
}

func (o *DcimRackTypesDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDcimRackTypesDeleteDefault creates a DcimRackTypesDeleteDefault with default headers values
func NewDcimRackTypesDeleteDefault(code int) *DcimRackTypesDeleteDefault {
	return &DcimRackTypesDeleteDefault{
		_statusCode: code,
	}
}

/*
DcimRackTypesDeleteDefault describes a response with status code -1, with default header values.

DcimRackTypesDeleteDefault dcim rack types delete default
*/
type DcimRackTypesDeleteDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this dcim rack types delete default response has a 2xx status code
func (o *DcimRackTypesDeleteDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim rack types delete default response has a 3xx status code
func (o *DcimRackTypesDeleteDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim rack types delete default response has a 4xx status code
func (o *DcimRackTypesDeleteDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim rack types delete default response has a 5xx status code
func (o *DcimRackTypesDeleteDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim rack types delete default response a status code equal to that given
func (o *DcimRackTypesDeleteDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim rack types delete default response
func (o *DcimRackTypesDeleteDefault) Code() int {
	return o._statusCode
}

func (o *DcimRackTypesDeleteDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcim_rack_types_delete default %s", o._statusCode, payload)
}

func (o *DcimRackTypesDeleteDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /dcim/rack-types/{id}/][%d] dcim_rack_types_delete default %s", o._statusCode, payload)
}

func (o *DcimRackTypesDeleteDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimRackTypesDeleteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
