// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDcimMacAddressesListParams creates a new DcimMacAddressesListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimMacAddressesListParams() *DcimMacAddressesListParams {
	return &DcimMacAddressesListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDcimMacAddressesListParamsWithTimeout creates a new DcimMacAddressesListParams object
// with the ability to set a timeout on a request.
func NewDcimMacAddressesListParamsWithTimeout(timeout time.Duration) *DcimMacAddressesListParams {
	return &DcimMacAddressesListParams{
		timeout: timeout,
	}
}

// NewDcimMacAddressesListParamsWithContext creates a new DcimMacAddressesListParams object
// with the ability to set a context for a request.
func NewDcimMacAddressesListParamsWithContext(ctx context.Context) *DcimMacAddressesListParams {
	return &DcimMacAddressesListParams{
		Context: ctx,
	}
}

// NewDcimMacAddressesListParamsWithHTTPClient creates a new DcimMacAddressesListParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimMacAddressesListParamsWithHTTPClient(client *http.Client) *DcimMacAddressesListParams {
	return &DcimMacAddressesListParams{
		HTTPClient: client,
	}
}

/*
DcimMacAddressesListParams contains all the parameters to send to the API endpoint

	for the dcim mac addresses list operation.

	Typically these are written to a http.Request.
*/
type DcimMacAddressesListParams struct {

	// ID.
	ID *string

	/* Limit.

	   Number of results to return per page.
	*/
	Limit *int64

	/* Offset.

	   The initial index from which to return the results.
	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the dcim mac addresses list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimMacAddressesListParams) WithDefaults() *DcimMacAddressesListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim mac addresses list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimMacAddressesListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) WithTimeout(timeout time.Duration) *DcimMacAddressesListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) WithContext(ctx context.Context) *DcimMacAddressesListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) WithHTTPClient(client *http.Client) *DcimMacAddressesListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) WithID(id *string) *DcimMacAddressesListParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) SetID(id *string) {
	o.ID = id
}

// WithLimit adds the limit to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) WithLimit(limit *int64) *DcimMacAddressesListParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) WithOffset(offset *int64) *DcimMacAddressesListParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the dcim mac addresses list params
func (o *DcimMacAddressesListParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *DcimMacAddressesListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ID != nil {

		// query param id
		var qrID string

		if o.ID != nil {
			qrID = *o.ID
		}
		qID := qrID
		if qID != "" {

			if err := r.SetQueryParam("id", qID); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
