// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// DcimRackTypesCreateReader is a Reader for the DcimRackTypesCreate structure.
type DcimRackTypesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimRackTypesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDcimRackTypesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimRackTypesCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimRackTypesCreateCreated creates a DcimRackTypesCreateCreated with default headers values
func NewDcimRackTypesCreateCreated() *DcimRackTypesCreateCreated {
	return &DcimRackTypesCreateCreated{}
}

/*
DcimRackTypesCreateCreated describes a response with status code 201, with default header values.

DcimRackTypesCreateCreated dcim rack types create created
*/
type DcimRackTypesCreateCreated struct {
	Payload *models.RackType
}

// IsSuccess returns true when this dcim rack types create created response has a 2xx status code
func (o *DcimRackTypesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim rack types create created response has a 3xx status code
func (o *DcimRackTypesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim rack types create created response has a 4xx status code
func (o *DcimRackTypesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim rack types create created response has a 5xx status code
func (o *DcimRackTypesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim rack types create created response a status code equal to that given
func (o *DcimRackTypesCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the dcim rack types create created response
func (o *DcimRackTypesCreateCreated) Code() int {
	return 201
}

func (o *DcimRackTypesCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/rack-types/][%d] dcimRackTypesCreateCreated %s", 201, payload)
}

func (o *DcimRackTypesCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/rack-types/][%d] dcimRackTypesCreateCreated %s", 201, payload)
}

func (o *DcimRackTypesCreateCreated) GetPayload() *models.RackType {
	return o.Payload
}

func (o *DcimRackTypesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RackType)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimRackTypesCreateDefault creates a DcimRackTypesCreateDefault with default headers values
func NewDcimRackTypesCreateDefault(code int) *DcimRackTypesCreateDefault {
	return &DcimRackTypesCreateDefault{
		_statusCode: code,
	}
}

/*
DcimRackTypesCreateDefault describes a response with status code -1, with default header values.

DcimRackTypesCreateDefault dcim rack types create default
*/
type DcimRackTypesCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this dcim rack types create default response has a 2xx status code
func (o *DcimRackTypesCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim rack types create default response has a 3xx status code
func (o *DcimRackTypesCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim rack types create default response has a 4xx status code
func (o *DcimRackTypesCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim rack types create default response has a 5xx status code
func (o *DcimRackTypesCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim rack types create default response a status code equal to that given
func (o *DcimRackTypesCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim rack types create default response
func (o *DcimRackTypesCreateDefault) Code() int {
	return o._statusCode
}

func (o *DcimRackTypesCreateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/rack-types/][%d] dcim_rack_types_create default %s", o._statusCode, payload)
}

func (o *DcimRackTypesCreateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/rack-types/][%d] dcim_rack_types_create default %s", o._statusCode, payload)
}

func (o *DcimRackTypesCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimRackTypesCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
