// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// NewDcimMacAddressesPartialUpdateParams creates a new DcimMacAddressesPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimMacAddressesPartialUpdateParams() *DcimMacAddressesPartialUpdateParams {
	return &DcimMacAddressesPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDcimMacAddressesPartialUpdateParamsWithTimeout creates a new DcimMacAddressesPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewDcimMacAddressesPartialUpdateParamsWithTimeout(timeout time.Duration) *DcimMacAddressesPartialUpdateParams {
	return &DcimMacAddressesPartialUpdateParams{
		timeout: timeout,
	}
}

// NewDcimMacAddressesPartialUpdateParamsWithContext creates a new DcimMacAddressesPartialUpdateParams object
// with the ability to set a context for a request.
func NewDcimMacAddressesPartialUpdateParamsWithContext(ctx context.Context) *DcimMacAddressesPartialUpdateParams {
	return &DcimMacAddressesPartialUpdateParams{
		Context: ctx,
	}
}

// NewDcimMacAddressesPartialUpdateParamsWithHTTPClient creates a new DcimMacAddressesPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimMacAddressesPartialUpdateParamsWithHTTPClient(client *http.Client) *DcimMacAddressesPartialUpdateParams {
	return &DcimMacAddressesPartialUpdateParams{
		HTTPClient: client,
	}
}

/*
DcimMacAddressesPartialUpdateParams contains all the parameters to send to the API endpoint

	for the dcim mac addresses partial update operation.

	Typically these are written to a http.Request.
*/
type DcimMacAddressesPartialUpdateParams struct {

	// Data.
	Data *models.MACAddress

	/* ID.

	   A unique integer value identifying this MAC address.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the dcim mac addresses partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimMacAddressesPartialUpdateParams) WithDefaults() *DcimMacAddressesPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim mac addresses partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimMacAddressesPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) WithTimeout(timeout time.Duration) *DcimMacAddressesPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) WithContext(ctx context.Context) *DcimMacAddressesPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) WithHTTPClient(client *http.Client) *DcimMacAddressesPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) WithData(data *models.MACAddress) *DcimMacAddressesPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) SetData(data *models.MACAddress) {
	o.Data = data
}

// WithID adds the id to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) WithID(id int64) *DcimMacAddressesPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim mac addresses partial update params
func (o *DcimMacAddressesPartialUpdateParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DcimMacAddressesPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
