// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDcimMacAddressesDeleteParams creates a new DcimMacAddressesDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimMacAddressesDeleteParams() *DcimMacAddressesDeleteParams {
	return &DcimMacAddressesDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDcimMacAddressesDeleteParamsWithTimeout creates a new DcimMacAddressesDeleteParams object
// with the ability to set a timeout on a request.
func NewDcimMacAddressesDeleteParamsWithTimeout(timeout time.Duration) *DcimMacAddressesDeleteParams {
	return &DcimMacAddressesDeleteParams{
		timeout: timeout,
	}
}

// NewDcimMacAddressesDeleteParamsWithContext creates a new DcimMacAddressesDeleteParams object
// with the ability to set a context for a request.
func NewDcimMacAddressesDeleteParamsWithContext(ctx context.Context) *DcimMacAddressesDeleteParams {
	return &DcimMacAddressesDeleteParams{
		Context: ctx,
	}
}

// NewDcimMacAddressesDeleteParamsWithHTTPClient creates a new DcimMacAddressesDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimMacAddressesDeleteParamsWithHTTPClient(client *http.Client) *DcimMacAddressesDeleteParams {
	return &DcimMacAddressesDeleteParams{
		HTTPClient: client,
	}
}

/*
DcimMacAddressesDeleteParams contains all the parameters to send to the API endpoint

	for the dcim mac addresses delete operation.

	Typically these are written to a http.Request.
*/
type DcimMacAddressesDeleteParams struct {

	/* ID.

	   A unique integer value identifying this MAC address.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the dcim mac addresses delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimMacAddressesDeleteParams) WithDefaults() *DcimMacAddressesDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim mac addresses delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimMacAddressesDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) WithTimeout(timeout time.Duration) *DcimMacAddressesDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) WithContext(ctx context.Context) *DcimMacAddressesDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) WithHTTPClient(client *http.Client) *DcimMacAddressesDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) WithID(id int64) *DcimMacAddressesDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim mac addresses delete params
func (o *DcimMacAddressesDeleteParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DcimMacAddressesDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
