// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pkorovin/go-netbox/netbox/models"
)

// DcimDevicesRenderConfigReader is a Reader for the DcimDevicesRenderConfig structure.
type DcimDevicesRenderConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimDevicesRenderConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDcimDevicesRenderConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimDevicesRenderConfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimDevicesRenderConfigOK creates a DcimDevicesRenderConfigOK with default headers values
func NewDcimDevicesRenderConfigOK() *DcimDevicesRenderConfigOK {
	return &DcimDevicesRenderConfigOK{}
}

/*
DcimDevicesRenderConfigOK describes a response with status code 200, with default header values.

DcimDevicesRenderConfigOK dcim devices render config o k
*/
type DcimDevicesRenderConfigOK struct {
	Payload *models.DeviceRenderConfig
}

// IsSuccess returns true when this dcim devices render config o k response has a 2xx status code
func (o *DcimDevicesRenderConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim devices render config o k response has a 3xx status code
func (o *DcimDevicesRenderConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim devices render config o k response has a 4xx status code
func (o *DcimDevicesRenderConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim devices render config o k response has a 5xx status code
func (o *DcimDevicesRenderConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim devices render config o k response a status code equal to that given
func (o *DcimDevicesRenderConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the dcim devices render config o k response
func (o *DcimDevicesRenderConfigOK) Code() int {
	return 200
}

func (o *DcimDevicesRenderConfigOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/devices/{id}/render-config/][%d] dcimDevicesRenderConfigOK %s", 200, payload)
}

func (o *DcimDevicesRenderConfigOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/devices/{id}/render-config/][%d] dcimDevicesRenderConfigOK %s", 200, payload)
}

func (o *DcimDevicesRenderConfigOK) GetPayload() *models.DeviceRenderConfig {
	return o.Payload
}

func (o *DcimDevicesRenderConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceRenderConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimDevicesRenderConfigDefault creates a DcimDevicesRenderConfigDefault with default headers values
func NewDcimDevicesRenderConfigDefault(code int) *DcimDevicesRenderConfigDefault {
	return &DcimDevicesRenderConfigDefault{
		_statusCode: code,
	}
}

/*
DcimDevicesRenderConfigDefault describes a response with status code -1, with default header values.

DcimDevicesRenderConfigDefault dcim devices render config default
*/
type DcimDevicesRenderConfigDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this dcim devices render config default response has a 2xx status code
func (o *DcimDevicesRenderConfigDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim devices render config default response has a 3xx status code
func (o *DcimDevicesRenderConfigDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim devices render config default response has a 4xx status code
func (o *DcimDevicesRenderConfigDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim devices render config default response has a 5xx status code
func (o *DcimDevicesRenderConfigDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim devices render config default response a status code equal to that given
func (o *DcimDevicesRenderConfigDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim devices render config default response
func (o *DcimDevicesRenderConfigDefault) Code() int {
	return o._statusCode
}

func (o *DcimDevicesRenderConfigDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/devices/{id}/render-config/][%d] dcim_devices_render_config default %s", o._statusCode, payload)
}

func (o *DcimDevicesRenderConfigDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/devices/{id}/render-config/][%d] dcim_devices_render_config default %s", o._statusCode, payload)
}

func (o *DcimDevicesRenderConfigDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimDevicesRenderConfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
