// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDcimRackTypesReadParams creates a new DcimRackTypesReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDcimRackTypesReadParams() *DcimRackTypesReadParams {
	return &DcimRackTypesReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDcimRackTypesReadParamsWithTimeout creates a new DcimRackTypesReadParams object
// with the ability to set a timeout on a request.
func NewDcimRackTypesReadParamsWithTimeout(timeout time.Duration) *DcimRackTypesReadParams {
	return &DcimRackTypesReadParams{
		timeout: timeout,
	}
}

// NewDcimRackTypesReadParamsWithContext creates a new DcimRackTypesReadParams object
// with the ability to set a context for a request.
func NewDcimRackTypesReadParamsWithContext(ctx context.Context) *DcimRackTypesReadParams {
	return &DcimRackTypesReadParams{
		Context: ctx,
	}
}

// NewDcimRackTypesReadParamsWithHTTPClient creates a new DcimRackTypesReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewDcimRackTypesReadParamsWithHTTPClient(client *http.Client) *DcimRackTypesReadParams {
	return &DcimRackTypesReadParams{
		HTTPClient: client,
	}
}

/*
DcimRackTypesReadParams contains all the parameters to send to the API endpoint

	for the dcim rack types read operation.

	Typically these are written to a http.Request.
*/
type DcimRackTypesReadParams struct {

	/* ID.

	   A unique integer value identifying this rack type.
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the dcim rack types read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimRackTypesReadParams) WithDefaults() *DcimRackTypesReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the dcim rack types read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DcimRackTypesReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the dcim rack types read params
func (o *DcimRackTypesReadParams) WithTimeout(timeout time.Duration) *DcimRackTypesReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the dcim rack types read params
func (o *DcimRackTypesReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the dcim rack types read params
func (o *DcimRackTypesReadParams) WithContext(ctx context.Context) *DcimRackTypesReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the dcim rack types read params
func (o *DcimRackTypesReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the dcim rack types read params
func (o *DcimRackTypesReadParams) WithHTTPClient(client *http.Client) *DcimRackTypesReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the dcim rack types read params
func (o *DcimRackTypesReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the dcim rack types read params
func (o *DcimRackTypesReadParams) WithID(id int64) *DcimRackTypesReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the dcim rack types read params
func (o *DcimRackTypesReadParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DcimRackTypesReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
