// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2020 The go-netbox Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package dcim

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/fbreckle/go-netbox/netbox/models"
)

// DcimMacAddressesCreateReader is a Reader for the DcimMacAddressesCreate structure.
type DcimMacAddressesCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DcimMacAddressesCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDcimMacAddressesCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDcimMacAddressesCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDcimMacAddressesCreateCreated creates a DcimMacAddressesCreateCreated with default headers values
func NewDcimMacAddressesCreateCreated() *DcimMacAddressesCreateCreated {
	return &DcimMacAddressesCreateCreated{}
}

/*
DcimMacAddressesCreateCreated describes a response with status code 201, with default header values.

DcimMacAddressesCreateCreated dcim mac addresses create created
*/
type DcimMacAddressesCreateCreated struct {
	Payload *models.MACAddress
}

// IsSuccess returns true when this dcim mac addresses create created response has a 2xx status code
func (o *DcimMacAddressesCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this dcim mac addresses create created response has a 3xx status code
func (o *DcimMacAddressesCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this dcim mac addresses create created response has a 4xx status code
func (o *DcimMacAddressesCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this dcim mac addresses create created response has a 5xx status code
func (o *DcimMacAddressesCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this dcim mac addresses create created response a status code equal to that given
func (o *DcimMacAddressesCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the dcim mac addresses create created response
func (o *DcimMacAddressesCreateCreated) Code() int {
	return 201
}

func (o *DcimMacAddressesCreateCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/mac-addresses/][%d] dcimMacAddressesCreateCreated %s", 201, payload)
}

func (o *DcimMacAddressesCreateCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/mac-addresses/][%d] dcimMacAddressesCreateCreated %s", 201, payload)
}

func (o *DcimMacAddressesCreateCreated) GetPayload() *models.MACAddress {
	return o.Payload
}

func (o *DcimMacAddressesCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MACAddress)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDcimMacAddressesCreateDefault creates a DcimMacAddressesCreateDefault with default headers values
func NewDcimMacAddressesCreateDefault(code int) *DcimMacAddressesCreateDefault {
	return &DcimMacAddressesCreateDefault{
		_statusCode: code,
	}
}

/*
DcimMacAddressesCreateDefault describes a response with status code -1, with default header values.

DcimMacAddressesCreateDefault dcim mac addresses create default
*/
type DcimMacAddressesCreateDefault struct {
	_statusCode int

	Payload interface{}
}

// IsSuccess returns true when this dcim mac addresses create default response has a 2xx status code
func (o *DcimMacAddressesCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this dcim mac addresses create default response has a 3xx status code
func (o *DcimMacAddressesCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this dcim mac addresses create default response has a 4xx status code
func (o *DcimMacAddressesCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this dcim mac addresses create default response has a 5xx status code
func (o *DcimMacAddressesCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this dcim mac addresses create default response a status code equal to that given
func (o *DcimMacAddressesCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the dcim mac addresses create default response
func (o *DcimMacAddressesCreateDefault) Code() int {
	return o._statusCode
}

func (o *DcimMacAddressesCreateDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/mac-addresses/][%d] dcim_mac-addresses_create default %s", o._statusCode, payload)
}

func (o *DcimMacAddressesCreateDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /dcim/mac-addresses/][%d] dcim_mac-addresses_create default %s", o._statusCode, payload)
}

func (o *DcimMacAddressesCreateDefault) GetPayload() interface{} {
	return o.Payload
}

func (o *DcimMacAddressesCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
